#!/usr/bin/env python3
"""Generate the SLURM job arrays for the QM9 re-run.

WHY EVERYTHING ABOVE ZERO NOISE HAS TO BE REDONE
------------------------------------------------
The noise map is keyed by TRAINING index, and write_data restarted its counter
for every split -- so validation and test molecules were handed the noise drawn
for the training molecule at the same position. Held-out labels were corrupted
contrary to the Methods, AND the corruption was attached to the wrong molecules.
Every QM9 R2 above zero noise was scored against a moving target.

Fixed in rust/src/main.rs (apply_noise flag, true only for the training call).
The fix is in the repo; the binary must be REBUILT on the cluster.

Results at zero noise are unaffected -- process_and_train.py switches the noise
path off for all splits at level 0. They are re-run here anyway because splicing
two runs is more error-prone than re-running one grid, and zero is 1/7th of the
cost.

WHAT CHANGED ON 2026-08-27, AND WHY THE OLD SCRIPTS COULD NOT RUN
-----------------------------------------------------------------
This generator was written against the noise scheme that has since been replaced
(NOISE_DESIGN.md). It emitted `--sigma` and `--noise-strategy`, and
process_and_train.py now refuses both BY NAME (:420-431) rather than ignoring
them, because a job written against the old scheme would otherwise run silently
under the new one where the level means something different. It also emitted
`-b` for the replicate count, and two representations -- mol2vec and one-hot
SMILES -- that were dropped from the study on 2026-08-26 and are refused by name
in parse_mmap (:1173, :1199). Every generated script would therefore have failed
at argument parsing, or in the reader.

Nothing generated by the old version is recoverable or worth recovering: the
.sh files are not in version control (SLURM scripts are copied to the cluster,
not committed), so this file IS the artefact.

WHAT A CONDITION IS NOW
-----------------------
The old six "strategies" were one strategy at six doses (RERUN_PLAN.md 2.2).
The replacement separates two things that were tangled together:

  --noise-shape      the shape of each individual draw   (gaussian, student_t, laplace)
  --noise-targeting  who gets hit and how hard           (uniform, grouped_wide,
                                                          grouped_shift, outlier, censoring)

and every combination delivers the SAME amount of noise at the same level, so
the conditions are comparable to each other. A "condition" below is one
(shape, targeting) pair plus the parameters that pair needs. The level grids
come from the range-finding run, NOISE_DESIGN.md 6.4 -- seven dose levels for
the zero-mean conditions, seven censoring fractions for censoring, which is not
zero-mean and cannot be dose-matched.

THE STAGES
----------
RERUN_PLAN.md 13.1, agreed 2026-08-26. The replicate seed depends only on the
replicate index, so stage 0 IS replicate 0 of stage 1 and is reused rather than
thrown away -- which is why --stage 1 starts at iteration 1 and why both stages
write to the same file.

  stage 0  screen     every model x every rep, the stage-1 conditions, 1 replicate
  stage 1  breadth    the same grid, replicates 1-9 appended to stage 0's
  stage 2  depth      chosen models x chosen reps, ALL conditions, 10 replicates

Stage 2 cannot be generated blind -- which models and representations go deep is
open (13.1 item 4) and cannot be chosen before stage 0 has run -- so --stage 2
requires --models and --reps explicitly.

THE GRID
--------
13 models x 6 representations x {conditions} x 7 levels x {replicates}.
Model and representation are the two factors of the variance decomposition, so
neither can be cut without gutting the paper's first question.

One array TASK per (condition, representation); one SCRIPT per model.
"""
import argparse
import json
import math
from pathlib import Path

# ---------------------------------------------------------------------------
# Representations
# ---------------------------------------------------------------------------
# The set was settled on 2026-08-26 and is enforced in the code: PDV
# (pdv), MHG-GNN, Avalon, ECFP4, ChemBERTa, Sort & Slice. mol2vec is
# deleted outright; one-hot SMILES and randomized SMILES still build but are
# refused by name in process_and_train.py parse_mmap, so a job that asked for
# them would raise rather than produce results with nowhere to go.
#
#   ALL_REPS  the six.
#   FP_REPS   binary fingerprints only. The Tanimoto kernel is defined on binary
#             vectors, so the Tanimoto GP can only run here.
ALL_REPS = ['ecfp4', 'pdv', 'mhggnn', 'avalon', 'chemberta', 'sns']
FP_REPS = ['ecfp4', 'sns']

# ---------------------------------------------------------------------------
# Noise conditions
# ---------------------------------------------------------------------------
# Level grids, NOISE_DESIGN.md 6.4, both set by the range-finding run (5.5).
# Below 0.2 of the label spread the models are indistinguishable from clean;
# 1.5 is kept because it is the only level where the conditions separate at all.
DOSE_LEVELS = '0.0 0.2 0.3 0.5 0.75 1.0 1.5'
# Censoring is swept on its own axis -- the fraction of labels clipped at the
# assay limit. There is no knee; damage accelerates smoothly, becoming serious
# around 20% and severe past 30%.
CENSOR_LEVELS = '0.0 0.10 0.20 0.25 0.30 0.40 0.50'

# WHICH CONDITIONS EXIST, AND WHICH RUN AT FULL GRID, IS NOT DECIDED HERE.
#
# noise_conditions.json is the settled set, and it is read by tests on both
# injectors. This generator reads it too, rather than restating it: a restatement
# is how the two injectors drifted apart for the life of the project, and a job
# script that runs a condition the study does not recognise is the same failure
# one layer up.
#
# What DOES belong here is the translation from a condition name to the
# command-line flags that produce it, and which level grid it is swept on. That
# is the generator's actual job.
#
# Only flags that DIFFER from the process_and_train.py default are passed. The
# rest are echoed in full by the injector on every call (the "Rust command:" line
# in the job output), so provenance is captured without this file restating --
# and eventually contradicting -- the defaults. The single-setting decisions
# (nu, the outlier fraction, which end censoring clips) come from the settled
# file, spelled out on the command line so the job log records them.
# WHICH PAIRS THE UNCERTAINTY WORK RUNS, read and never restated.
#
# The author settled this on 2026-08-29: four models, three representations, the
# variational network on ChemBERTa alone. The same pairs on all four datasets,
# which was the ruling of 2026-08-28 -- "the same thing that happens on QM9
# happens on the others".
#
# It had been applied to the laboratory job generator and to nothing else. QM9
# has no uncertainty run of its own; its uncertainty rows fall out of this grid,
# so every model that emits one was cross-fitted on every representation. That is
# 11 models by 6 representations against the laboratory's 10 pairs, and the two
# halves could not be compared pair for pair.
#
# This restricts ONLY the uncertainty pass. Every model still trains on every
# representation for the accuracy results, the retention curves and the variance
# decomposition, none of which read an uncertainty column.
UNCERTAINTY_PAIRS_FILE = Path(__file__).resolve().parent.parent / 'uncertainty_pairs.json'
_PAIRS = json.loads(UNCERTAINTY_PAIRS_FILE.read_text())
# QM9 roster label -> the representations that model runs the uncertainty pass on.
UNCERTAINTY_PAIRS = {}
_pair_reps_all = [r['qm9'] for r in _PAIRS['representations']]
_canon_to_qm9_rep = {r['canonical']: r['qm9'] for r in _PAIRS['representations']}
for _m in _PAIRS['models']:
    _only = _PAIRS.get('model_representations', {}).get(_m['canonical'])
    UNCERTAINTY_PAIRS[_m['qm9']] = ([_canon_to_qm9_rep[c] for c in _only]
                                    if _only else list(_pair_reps_all))

# HOW MANY OF THE INNER FOLDS ARE ACTUALLY SCORED, per model.
#
# The out-of-fold pass splits the training molecules into `--oof-folds` folds and
# refits once per fold, so every molecule is scored by a model that never saw its
# label. Scoring FEWER folds than were cut keeps that property exactly -- the
# molecules in a scored fold are still scored out of fold -- and costs one refit
# per scored fold instead of five. The molecules in the unscored folds are left
# blank, so it buys the cost back with coverage, not with correctness.
#
# NGBoost is the only model that needs it, and it needs it because it pays for
# two different questions at once. Three seeds give it a model-uncertainty term
# at all (a single distributional fit has nothing to disagree with, added
# 2026-08-30 in c2aec9d); the out-of-fold pass gives per-molecule rows whose
# labels were corrupted. The two multiply: three seeds times six fits is
# EIGHTEEN fits per training run, which prices the main grid task at 606 hours --
# 25 days against a 30-day partition limit, with nothing spare for a hiccup.
#
# Three seeds and one scored fold is six fits, 202 hours, which is exactly what
# NGBoost cost before the seeds landed. What is given up is per-molecule coverage
# on NGBoost: a fifth of the training molecules get an out-of-fold row instead of
# all of them. That is the input to the which-molecules question, which NGBoost is
# not the model that answers -- and the decomposition claim it IS on the list for
# is a population statement that does not read those rows at all
# (uncertainty_pairs.json, `_which_question_this_answers`).
#
# Set to 0, or leave a model out, to score every fold that was cut.
# EMPTY, and that is the current state rather than a missing feature. It existed
# for one day because NGBoost's seed ensemble made it eighteen fits per training
# run -- 606 hours, 25 days against a 30-day limit -- and scoring one fold took
# that back to six. The ensemble was withdrawn on measurement the next day
# (RERUN_PLAN.md 2.30), so NGBoost is six fits again on its own and every model
# scores every fold it cuts. The machinery stays because the lever is real and
# the wall-clock guard that found the problem is worth keeping pointed at it.
OOF_FOLDS_SCORED = {}

NOISE_CONDITIONS_FILE = Path(__file__).resolve().parent.parent / 'noise_conditions.json'
_SETTLED = json.loads(NOISE_CONDITIONS_FILE.read_text())
_SETTINGS = _SETTLED['settings_that_follow']

CONDITION_FLAGS = {
    'gaussian':        ('--noise-shape gaussian --noise-targeting uniform', DOSE_LEVELS),
    'grouped_wider':   ('--noise-shape gaussian --noise-targeting grouped_wide', DOSE_LEVELS),
    'grouped_shifted': ('--noise-shape gaussian --noise-targeting grouped_shift', DOSE_LEVELS),
    'censoring':       (f"--noise-targeting censoring "
                        f"--censor-side {_SETTINGS['censor_side']}", CENSOR_LEVELS),
    'student_t_nu5':   (f"--noise-shape student_t --noise-targeting uniform "
                        f"--nu {_SETTINGS['nu']}", DOSE_LEVELS),
    'outlier_p10':     (f"--noise-shape gaussian --noise-targeting outlier "
                        f"--outlier-p {_SETTINGS['outlier_p']}", DOSE_LEVELS),
    'laplace':         ('--noise-shape laplace --noise-targeting uniform', DOSE_LEVELS),
}

# The clean level is run ONCE, under the reference condition, and copied into the
# others by copy_zero_rows.py after the array finishes.
#
# At level 0 the pipeline does not add noise at all -- it switches the noise step
# off for every split -- and the replicate seed depends only on the replicate
# number, so the clean run is bit-identical whichever condition it is labelled
# with. Measured on 400 QM9 molecules with the random forest on ECFP4: all four
# conditions returned R2 = 0.7579128047581825 and RMSE = 0.5176004014184159, to
# the last digit.
#
# Running it four times costs 11% of the QM9 grid to recompute a number we
# already have. It cannot simply be dropped, because auc_norm divides each
# condition's curve by that condition's OWN clean accuracy, so a condition with
# no clean row has nothing to divide by -- hence the copy.
REFERENCE_CONDITION = 'gaussian'

# CONDITIONS THAT RUN THEIR OWN CLEAN LEVEL, on top of the reference.
#
# The copy above is sound for ACCURACY and unsound for the uncertainty question,
# and nobody joined the two facts up. copy_zero_rows.py refuses any file whose
# name contains `_uncertainty_values` -- correctly, because it cannot invent
# per-molecule numbers -- so a condition without its own clean level gets its
# accuracy baseline and no uncertainty baseline.
#
# That baseline is not optional and it is not borrowable. "Is the model less
# certain where the labels are unreliable" is answered by correlating the
# predicted uncertainty against the level-free shape of the noise, then
# SUBTRACTING the same correlation at level zero -- because a model can look
# less certain about those molecules for a boring reason, such as their being
# the large ones. The zero-level model saw the same labels and no corruption, so
# its correlation is exactly that confound.
#
# Borrowing the reference condition's clean run does not work: the shape column
# is what differs between conditions at level zero, and the reference condition
# hits every molecule equally, so it has no shape to subtract. Without its own
# clean row the effect comes out NaN -- an empty table, not a wrong one.
#
# WHY ONLY CENSORING. Author's decision, 2026-08-28, on the evidence in
# RERUN_PLAN.md 3.1f. Of the seven conditions, four deliver the same amount to
# every molecule, so their shape is flat and the correlation is undefined rather
# than zero. Of the three with a shape, `grouped_wider` is keyed to the scaffold
# group and the out-of-fold pass splits on that SAME array, so the group is
# hidden from the fit being asked about; `outlier_p10` picks its victims at
# random. Both are structural nulls whatever is measured. Censoring is keyed to
# the label, so it is learnable on any split -- it is the only condition on which
# the question has an answer, and the only one whose clean level buys something.
#
# Cost: censoring runs on about five model-and-representation pairs on QM9, so
# this is roughly 45 extra training runs across the main grid. Adding the two
# nulls as well would be about 5.3% of the screen and of the main grid, and buys
# a measured zero where the design already predicts one.
NEEDS_OWN_CLEAN_LEVEL = {'censoring'}


def build_uncertainty_block(model, unc_reps, oof_folds, oof_scored=0):
    """The shell that decides whether THIS array task runs the uncertainty pass.

    The pass costs `oof_folds` extra fits on top of the training run, and it is
    worth spending only on the settled pairs (`uncertainty_pairs.json`). Which
    representation a task has is not known until the array dispatches, so the
    choice is a case statement rather than a flag baked into the command.

    A model that emits no per-molecule uncertainty at all gets an empty variable
    and a line saying so, rather than nothing -- a silent absence and a decision
    read the same in a job log.
    """
    if not unc_reps:
        return ('OOF_FLAGS=""\n'
                f'echo "=== out-of-fold pass: {model} is on no settled pair here, '
                'so test rows only"')
    cases = ' | '.join(unc_reps)
    return (
        '# The out-of-fold uncertainty pass, on the settled pairs only\n'
        '# (uncertainty_pairs.json). It refits once per inner fold, so a run on a\n'
        '# settled pair costs %d fits instead of one -- a task on any other\n'
        '# representation must not pay for it. `-u True` is NOT restricted: it is\n'
        '# free and it writes the test rows either way.\n'
        'case "$rep" in\n'
        '  %s) OOF_FLAGS="--oof-folds %d%s" ;;\n'
        '  *) OOF_FLAGS="" ;;\n'
        'esac\n'
        'if [ -n "$OOF_FLAGS" ]; then\n'
        '    echo "=== out-of-fold pass: settled pair %s/$rep -> $OOF_FLAGS"\n'
        'else\n'
        '    echo "=== out-of-fold pass: %s/$rep is not a settled pair, test rows only"\n'
        'fi' % (1 + (oof_scored or oof_folds), cases, oof_folds,
                (f' --oof-folds-scored {oof_scored}' if oof_scored else ''),
                model, model))


def levels_for(name, levels):
    """The levels a condition actually runs.

    The reference condition runs the clean one, and so does any condition that
    needs its OWN clean level as the control for the uncertainty question. Every
    other condition has its clean ACCURACY row filled in afterwards by
    copy_zero_rows.py, which is sound because at level zero the fit is
    bit-identical whichever condition labels it.
    """
    if name == REFERENCE_CONDITION or name in NEEDS_OWN_CLEAN_LEVEL:
        return levels
    return ' '.join(v for v in levels.split() if float(v) != 0.0)


# Conditions the settled file restricts to a subset of model-and-representation pairs on
# QM9. Censoring is the only one today: the question there is how big the effect is, not
# which model resists it best, so it runs on about five pairs instead of all 78
# (RERUN_PLAN.md 13.13). The scope is QM9 only -- censoring stays a full condition in the
# uncertainty runs. Read from the file rather than hardcoded, so the file stays the place
# the decision lives.
PAIR_SUBSET_CONDITIONS = {
    c['name']: c["scope"]
    for g in ('stage_1_full_grid', 'stage_2_depth_only')
    for c in _SETTLED[g]
    if c.get("scope", {}).get('mode') == 'pair_subset'
}

STAGE1_CONDITIONS = [c['name'] for c in _SETTLED['stage_1_full_grid']]
STAGE2_CONDITIONS = STAGE1_CONDITIONS + [c['name'] for c in _SETTLED['stage_2_depth_only']]

# name -> (flags, level grid, runs at full grid in stage 1, why -- the settled
# file's own words, so the job script header carries the reason with it)
CONDITIONS = {}
for _group in ('stage_1_full_grid', 'stage_2_depth_only'):
    for _entry in _SETTLED[_group]:
        _name = _entry['name']
        if _name not in CONDITION_FLAGS:
            raise SystemExit(
                f"{NOISE_CONDITIONS_FILE.name} names the condition '{_name}' but this generator "
                f"does not know how to ask for it. Add it to CONDITION_FLAGS, or the study runs "
                f"a set the job scripts cannot produce.")
        _flags, _levels = CONDITION_FLAGS[_name]
        CONDITIONS[_name] = (_flags, levels_for(_name, _levels),
                             _group == 'stage_1_full_grid', _entry['why'])

_unused = sorted(set(CONDITION_FLAGS) - set(CONDITIONS))
if _unused:
    raise SystemExit(
        f"this generator can emit condition(s) {_unused} that {NOISE_CONDITIONS_FILE.name} does "
        f"not run. Either add them there with their evidence, or take them out of "
        f"CONDITION_FLAGS -- a condition nobody decided to run is how an unjustified cell gets "
        f"into the study.")

# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------
# label -> (extra CLI flags, tier, hours per 110 training runs, note, reps)
# The label is the filename suffix and MUST match what the figure script parses:
# generate_paper_figures_v2.py:592-615 maps '<base>_bnn_full_variational' to the
# VBLL models, so that spelling is load-bearing. It is also checked against
# check_environment.py QM9_MODELS by `check_environment.py --audit-roster`.
#
# The hours column is quoted PER 110 TRAINING RUNS, which is what the old
# eleven-level ten-replicate design asked of each task. The actual grid is
# smaller now and varies by stage, so the wall clock is scaled from it below
# rather than carried as a fixed number that would silently over-request.
MODELS = {
    'rf':                       ('-m rf',        1, 23, 'random forest', ALL_REPS),
    'xgboost':                  ('-m xgboost',   1, 23, '', ALL_REPS),
    'lgb':                      ('-m lgb',       1, 23, 'LightGBM', ALL_REPS),
    'svm':                      ('-m svm',       1, 35, 'RBF kernel on every representation', ALL_REPS),
    # ONE FIT PER RUN, back to 47 hours. The seed ensemble was queued on
    # 2026-08-30 and withdrawn on measurement the next day: NGBoost's seed
    # reaches only minibatch_frac and col_sample, both pinned at 1.0, so three
    # seeds are the same fit and the spread between them is 150 to 3,581 times
    # smaller than the aleatoric term -- and it RISES with the noise level
    # (RERUN_PLAN.md 2.30). `ngboost_ensemble_seeds` is 1 in the shared spec, so
    # the tripled wall clock this line carried for one day is wrong again.
    'ngboost':                  ('-m ngboost -u True', 1, 47, 'slowest tree model; emits a per-molecule aleatoric term, and no epistemic one -- one distributional fit has nothing to disagree with (RERUN_PLAN.md 2.30)', ALL_REPS),
    'dnn':                      ('-m dnn',       1, 35, '', ALL_REPS),
    'mlp':                      ('-m mlp',       1, 35, '', ALL_REPS),
    'dnn_bnn_full':             ('-m dnn --bayesian-transformation full -u True', 2, 47, 'BNN-alpha', ALL_REPS),
    'mlp_bnn_full':             ('-m mlp --bayesian-transformation full -u True', 2, 47, 'BNN-beta', ALL_REPS),
    'dnn_bnn_full_variational': ('-m dnn --bayesian-transformation full_variational -u True', 2, 47, 'VBLL-alpha (figure script reads this as dnn_vbll)', ALL_REPS),
    'mlp_bnn_full_variational': ('-m mlp --bayesian-transformation full_variational -u True', 2, 47, 'VBLL-beta (figure script reads this as mlp_vbll)', ALL_REPS),
    # Outside the ANOVA roster, but they feed figures and supplementary tables:
    'qrf':        ('-m qrf -u True', 3, 23, 'not in the ANOVA (rho 0.996 with rf) but the best error-ranker', ALL_REPS),
    'gauche_rbf': ('-m gauche --kernel rbf -u True', 3, 47, 'RBF GP on EVERY rep, so the GP can finally enter the cross-rep ANOVA', ALL_REPS),
    'gauche':     ('-m gauche --kernel tanimoto -u True', 3, 47,
                   'Tanimoto GP. Only defined on BINARY fingerprints, so ecfp4/sns only. '
                   'This is the RBF-vs-Tanimoto head-to-head; the figure script gives it its '
                   'own colour and marker and labels it GP', FP_REPS),
    # ---------------------------------------------------------------------
    # THE DECOMPOSITION MODELS, added 2026-08-28.
    #
    # Not one model above reports BOTH components per molecule: the forests do
    # now, but every other one has a data-noise term that is either absent or a
    # single number broadcast onto every row, and a constant correlates with
    # per-molecule injected noise at exactly zero however good the model is
    # (RERUN_PLAN.md 5.5a point 5). These two are the ones that can answer the
    # question at all. Both were written and neither had ever been in a job
    # script, so neither has run under a real job -- which is itself worth
    # knowing before the grid is committed.
    # ---------------------------------------------------------------------
    'heteroscedastic_gp': ('-m het_gp --kernel rbf -u True', 3, 47,
                   'Gaussian process whose observation noise is predicted per molecule by a '
                   'second network. Measured locally at R2 0.5315 against 0.5318 for the '
                   'ordinary one on identical data, so it is free, and its data-noise term '
                   'tracks the true noise size at rho +0.73 while its model term sits at '
                   '-0.16 (RERUN_PLAN.md 5.5e)', ALL_REPS),
    'dnn_bnn_full_variational_hetero': (
                   '-m dnn --bayesian-transformation full_variational '
                   '--heteroscedastic-vbll -u True', 3, 47,
                   'VBLL-alpha with a noise head, so its data-noise term varies per molecule '
                   'instead of being one number per fit (RERUN_PLAN.md 5.5f)', ALL_REPS),
    'mlp_bnn_full_variational_hetero': (
                   '-m mlp --bayesian-transformation full_variational '
                   '--heteroscedastic-vbll -u True', 3, 47,
                   'VBLL-beta with a noise head', ALL_REPS),
}

# Excluded from EVERY figure by GLOBAL_MODELS_EXCLUDE, so re-running them
# produces files nothing reads. They survive only in
# table1_supp_simple_effects_all_reps.csv, which runs with no exclusions.
# Off by default; --include-excluded turns them on.
EXCLUDED_MODELS = {
    # COMMENTED OUT 2026-08-28, on the author's instruction. Excluding them was
    # not enough: --include-excluded turned them back on, and process_and_train.py
    # now refuses `-m conformal` by name, so those three scripts would have been
    # written and then died at the first line. Removed here rather than left to
    # fail on the cluster (RERUN_PLAN.md 2.20).
    # 'conformal_rf':             ('-m conformal --cp-base-model rf -u True',  4, 35, 'conformal wrapper (rho > 0.99 with rf)', ALL_REPS),
    # 'conformal_qrf':            ('-m conformal --cp-base-model qrf -u True', 4, 35, 'conformal wrapper', ALL_REPS),
    # 'conformal_dnn':            ('-m conformal --cp-base-model dnn -u True', 4, 47, 'conformal wrapper', ALL_REPS),
    # `last` matched no branch in models.py, which tests `last_layer`. The value
    # fell through, no Bayesian layer was applied, and the deterministic network
    # that resulted was put through 100 forward passes in eval mode -- all
    # identical, uncertainty exactly zero, written to a file the figure script
    # reads as a last-layer BNN. process_and_train.py now refuses an
    # unrecognised value by name, so these two would not start at all.
    'dnn_bnn_last':             ('-m dnn --bayesian-transformation last_layer -u True', 4, 47, 'last-layer BNN (no significant gain over base)', ALL_REPS),
    'mlp_bnn_last':             ('-m mlp --bayesian-transformation last_layer -u True', 4, 47, 'last-layer BNN', ALL_REPS),
    'dnn_bnn_variational':      ('-m dnn --bayesian-transformation variational -u True', 4, 47, 'pre-VBLL variational (was identical to last-layer, a bug)', ALL_REPS),
    'mlp_bnn_variational':      ('-m mlp --bayesian-transformation variational -u True', 4, 47, 'pre-VBLL variational', ALL_REPS),
    'flexible_dnn':             ('-m flexible_dnn', 4, 35, 'architecture variant, not discussed in the paper', ALL_REPS),
}

QSAR_DIR = '/data/stat-cadd/scat9264/qsar_qm_models'

TEMPLATE = '''#!/bin/bash
# ============================================================================
# QM9 re-run — stage {stage} — model: {model}
# {note}
# ============================================================================
# Array task -> (noise condition, representation).
#   {n_cond} conditions x {n_rep} representations = {n_tasks} tasks
#   each task = {n_lev} noise levels x {n_reps_run} replicate(s) = {runs} training runs
#
# Conditions in this stage: {cond_list}
# Replicates: {n_reps_run}, numbered {first_iter}..{last_iter}. The replicate seed
# depends only on the replicate index, so these are exchangeable with a run made
# at any other time and append to the same file.
#
# REQUIRES the rebuilt rust binary (the held-out-noise fix). Run
# `cargo build --release` in {qsar_dir}/rust FIRST -- see RUNBOOK.
#
# --account and --partition are LIVE STATE; pass them at submit time:
#   sbatch --account=<acct> --partition=medium --array=0-{last}%{throttle} {script_name}
#
# Resubmit only failed indices:
#   sbatch --account=<acct> --partition=medium --array=3,17 {script_name}
# ============================================================================
#SBATCH --job-name=qm9{stage}_{jobslug}
#SBATCH --output=qm9{stage}_{jobslug}_%A_%a.out
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
#SBATCH --time={hours}:59:00
#SBATCH --mail-user=adelaide.punt@stcatz.ox.ac.uk
#SBATCH --mail-type=FAIL

set -uo pipefail

# ---------------------------------------------------------------------------
# WAIT A RANDOM MOMENT BEFORE DOING ANYTHING. This is not politeness.
#
# The KeOps library, which arrives with the Gaussian-process stack, runs
# `c++ --version` at IMPORT time and writes the answer to a HARD-CODED path:
# /tmp/compiler_version.txt. It then reads that file and deletes it. Two
# processes importing within the same instant race: one deletes the file while
# the other is between checking it exists and opening it, and the second dies
# with FileNotFoundError before a single molecule is read.
#
# Jobs sharing a node share /tmp, and an array releases its tasks together, so
# this hits real runs. The failure names a missing file in /tmp and says
# nothing about chemistry, and because it happens during import the task
# produces NO output at all -- it looks like a task that never started.
#
# TMPDIR does not help: the path is a literal inside the library, not taken
# from the environment. Staggering submission does not help either, because the
# queue decides when tasks actually start. A random wait inside the task is the
# only lever this side controls (found 2026-08-30, RERUN_PLAN.md 2.25).
sleep $(( RANDOM % 600 ))

# micromamba has never worked on this cluster -- setup.sh has always fallen
# through to its conda branch. The two `export MAMBA_EXE=...` lines that used to
# sit here were dead: the hook failed, and because this script runs under
# `set -uo pipefail` with no `-e`, the failure did not stop anything. The task
# simply carried on unactivated, in whatever python was on PATH.
cd {qsar_dir}
. setup.sh

# Activation is not optional, and until now nothing checked it. An unactivated
# task falls through to the system Anaconda at /apps/system/..., which has no
# gpytorch, no quantile_forest and no ngboost -- so the job runs, finds nothing
# to do, and produces no rows. That is what happened to 12822693 and 12822694
# (RERUN_PLAN.md §2.8d). Confirmed on the cluster 2026-08-26.
if [ -z "${{CONDA_PREFIX:-}}" ]; then
    echo "ERROR: setup.sh did not activate an environment (CONDA_PREFIX unset)."
    exit 2
fi

# setup.sh refuses to install the extras from inside an array task, because 294
# tasks compiling torchsort into one site-packages is the failure it exists to
# prevent. When it refuses, the environment is NOT the one env.yml describes and
# this job must stop rather than train in it -- an under-provisioned run that
# produces rows is worse than one that does not start.
if [ "${{SETUP_EXTRAS_REFUSED:-0}}" = "1" ]; then
    echo "ERROR: the environment does not match the recipe and setup.sh refused"
    echo "       to repair it from an array task. Run '. ./setup.sh' once in an"
    echo "       interactive allocation, then resubmit this array."
    exit 2
fi
PY_PATH="$(command -v python)"
case "$PY_PATH" in
    "$CONDA_PREFIX"/*) : ;;
    *)
        echo "ERROR: python is $PY_PATH, which is not inside the activated"
        echo "       environment ($CONDA_PREFIX)."
        case "$PY_PATH" in
            /apps/system/*)
                echo "       That is the system Anaconda. It has no gpytorch, no"
                echo "       quantile_forest and no ngboost, so this job would run,"
                echo "       find nothing to do, and write no rows." ;;
        esac
        exit 2 ;;
esac
# The test above cannot fail once setup.sh has run: setup.sh:124 prepends
# $CONDA_PREFIX/bin to PATH, so python resolves inside the prefix whichever
# environment was activated. It still catches an unset CONDA_PREFIX, which is
# the case that actually bit us -- but on its own it would pass a task that
# activated the WRONG environment, so the name is checked too. This literal
# must track ENV_NAME in setup.sh.
if [ "$(basename "$CONDA_PREFIX")" != "env_test" ]; then
    echo "ERROR: the active environment is $(basename "$CONDA_PREFIX"), not env_test"
    echo "       (CONDA_PREFIX=$CONDA_PREFIX). setup.sh activated the wrong one."
    exit 2
fi
echo "=== interpreter: $PY_PATH  (CONDA_PREFIX=$CONDA_PREFIX)"

# A private scratch directory per task.
#
# Hygiene, not a fix for any known defect here: joblib, matplotlib, numba and
# the HuggingFace cache all honour TMPDIR, and a fixed-name temp file shared by
# concurrent array tasks is the defect class that produced the config.json race.
# This closes the whole class cheaply.
#
# It does NOT fix the one instance found while testing: keopscore (gpytorch ->
# pykeops) hardcodes /tmp/compiler_version.txt and /tmp/brew_prefix.txt, writing
# and deleting them during import, so two simultaneous imports race and one dies
# with FileNotFoundError. TMPDIR is ignored by that code. It is guarded by
# platform.system() == "Darwin", so it cannot fire on this cluster -- it is a
# macOS-only problem, and it is why the two-task half of
# scripts/test_config_isolation.py skips on a laptop.
export TMPDIR="${{TMPDIR:-/tmp}}/qsar_${{SLURM_JOB_ID:-$$}}_${{SLURM_ARRAY_TASK_ID:-0}}"
mkdir -p "$TMPDIR"
trap 'rm -rf "$TMPDIR"' EXIT


# The binary carries the held-out-noise fix. Refuse to run without it rather
# than silently regenerating the same invalid results.
if [ ! -x rust/target/release/rust_processor ]; then
    echo "ERROR: rust/target/release/rust_processor missing. Run:"
    echo "  cd {qsar_dir}/rust && cargo build --release"
    exit 2
fi

# QM9 MUST ALREADY BE PROCESSED. Do not let a job build it.
#
# torch_geometric's QM9 processes data/QM9/raw into processed/data_v3.pt on first
# access, and it takes NO lock. The runbook deletes that directory (the ChemBERTa
# encoder change moved the record layout, so anything cached before it decodes
# every later field at the wrong offset) -- and if the array is then submitted
# cold, all 294 tasks build the same file into the same path at once. The cheap
# outcome is 294x the work; the expensive one is a task loading a .pt another task
# is still writing.
#
# Same shape as the setup.sh extras guard: the warm-up belongs in the interactive
# allocation, once, before any submission. This makes that ordering a property of
# the job rather than of whoever remembered the runbook.
if [ ! -f data/QM9/processed/data_v3.pt ]; then
    echo "ERROR: data/QM9/processed/data_v3.pt is missing, so this task would"
    echo "       process QM9 itself -- and so would every other task in the array,"
    echo "       into the same file, with no lock between them."
    echo "  Warm it ONCE in an interactive allocation before submitting, by running"
    echo "  the smoke task in RUNBOOK section 6 -- it loads QM9 as a side effect."
    echo "  Do NOT let the array build it."
    exit 2
fi

cd scripts

# The interpreter has to be able to BUILD what this job is about to ask for.
# Jobs 12822693 and 12822694 (2026-08-19) ran to completion and produced nothing
# because gpytorch was missing: the experiment list came out empty, five folds
# looped over nothing, and the job crashed reading its own empty output. This
# costs seconds and answers that before the queue does (RERUN_PLAN.md §2.8d).
python check_environment.py --models {model} || {{
    echo "ERROR: this interpreter cannot build model '{model}'. See the output above."
    exit 2
}}

CONDS=({cond_list})
REPS=({reps})

n_rep=${{#REPS[@]}}
n_tasks=$(( ${{#CONDS[@]}} * n_rep ))
i="${{SLURM_ARRAY_TASK_ID:-0}}"
if [ -z "${{SLURM_ARRAY_TASK_ID:-}}" ]; then
    echo "WARNING: not an array job — running task 0 only. Submit with --array=0-$(( n_tasks - 1 ))%N"
fi
if [ "$i" -ge "$n_tasks" ]; then
    echo "ERROR: task $i is out of range (0..$(( n_tasks - 1 )))"; exit 2
fi
if [ -z "${{SLURM_JOB_PARTITION:-}}" ]; then
    echo "ERROR: no partition. Submit with --partition=medium (see RUNBOOK)."; exit 2
fi

rep="${{REPS[$(( i % n_rep ))]}}"
cond="${{CONDS[$(( i / n_rep ))]}}"

# Each condition is a (shape, targeting) pair plus whatever that pair needs, and
# its own level grid -- censoring is a fraction of labels clipped, not a dose, so
# it cannot share the others' axis. Only flags that differ from the
# process_and_train.py default are passed; the injector echoes the full parameter
# set on every call, so the run log carries the provenance.
#
# A case statement rather than an associative array: associative arrays need
# bash 4, and this file is also smoke-tested on macOS, where /bin/bash is 3.2.
case "$cond" in
{cond_cases}
  *) echo "ERROR: unknown noise condition '$cond'"; exit 2 ;;
esac

OUT="../results/anova_${{cond}}_${{rep}}_{model}.csv"

echo "=== task $i: model={model} condition=$cond rep=$rep"
echo "=== noise: $NOISE_FLAGS"
echo "=== levels: $LEVELS"
echo "=== replicates: {n_reps_run} starting at {first_iter}"
echo "=== out: $OUT"
echo "=== started: $(date)"

# --use-best-params is what lets a tuned hyperparameter reach a model AT ALL.
# All twelve places models/models.py reads the tuned files sit behind it, and
# until 2026-08-28 no script this generator wrote passed it -- so the sweep could
# finish, the winners could be written to results/, and the grid would still have
# trained on the shared defaults with nothing saying so.
#
# THE DECISION IS MADE ONCE, HERE, AND NOT AGAIN.
#
# load_best_hyperparameters re-reads the two files inside EVERY training run, and
# a task runs one per (noise level, replicate). The author's plan is to submit
# while the tuning sweep is still going and let the files land during the queue
# wait, so without this block a task in flight when they appear would produce ONE
# degradation curve whose early noise levels were fitted at the shared defaults
# and whose later levels were fitted at the tuned setting. auc_norm is a statistic
# OF that curve, so it would measure neither. Different array tasks write
# different files, so there would be no duplicate row for the deduplication to
# reveal, and nothing downstream reads params_source -- the figure script warns on
# a mixed spec_hash, which cannot see this, because the hash covers only the
# shared spec.
#
# Deciding here means a task is entirely tuned or entirely default, whichever was
# true when it started, and the row's params_source says which. It is safe with no
# tuned files present: load_best_hyperparameters names the missing file and
# returns None. It is NOT a silent switch either way.
#
# RESIDUAL HAZARD, and it is operational rather than code: --write-master is not
# the only writer of those two files. confirm_tuned_on_validation_datasets.py
# --prune rewrites BOTH after they exist, dropping pairings the shared default
# beat. Running that WHILE the grid is running would change the setting under a
# task that had already decided to use it. Do not run --prune against a live grid.
TUNED_FLAG=""
if [ -f ../results/master_tuned_hyperparameters.json ] \\
   && [ -f ../results/hyperparameter_decisions.json ]; then
    TUNED_FLAG="--use-best-params"
    echo "=== tuned hyperparameters: PRESENT at task start -> --use-best-params"
else
    echo "=== tuned hyperparameters: ABSENT at task start -> shared defaults for this whole task"
fi

{unc_block}
python -u process_and_train.py -d QM9 -t homo_lumo_gap \\
    {flags} $OOF_FLAGS \\
    -r "$rep" \\
    --noise-level $LEVELS \\
    --dose-units spread \\
    $NOISE_FLAGS \\
    -n {sample_size} \\
    --repetitions {n_reps_run} \\
    --start-iteration {first_iter} \\
    -s scaffold \\
    --normalize True \\
    $TUNED_FLAG \\
    -f "$OUT"

status=$?
echo "=== finished: $(date)  exit=$status"
exit $status
'''


# Stage defaults, RERUN_PLAN.md §13.1. Stage 0 is replicate 0 of stage 1, so
# stage 1 starts at iteration 1 and both write to the same file.
# The screen and the main grid default to the conditions that run on all 78 pairs, minus
# anything the settled file restricts to a few pairs. Censoring is asked for by name, on
# named models and reps, or it does not run -- rather than the default invocation refusing
# and the next person working around the refusal.
_ALL_PAIRS = [c for c in STAGE1_CONDITIONS if c not in PAIR_SUBSET_CONDITIONS]
# The deep run drops them too. Censoring has its own run on its own five pairs, so
# including it here would either refuse (the deep run is more pairs than its subset) or
# quietly run it at deep-run breadth, which is the cost the subset decision removed.
_DEEP = [c for c in STAGE2_CONDITIONS if c not in PAIR_SUBSET_CONDITIONS]

STAGE_DEFAULTS = {
    0: dict(replicates=1,  start=0, conditions=_ALL_PAIRS),
    1: dict(replicates=9,  start=1, conditions=_ALL_PAIRS),
    2: dict(replicates=10, start=0, conditions=_DEEP),
}


def build_case_block(tags):
    """The bash case statement that turns a condition tag into flags and levels."""
    lines = []
    for tag in tags:
        flags, levels, _, why = CONDITIONS[tag]
        lines.append(f'  # {why}')
        lines.append(f'  {tag}) NOISE_FLAGS="{flags}"; LEVELS="{levels}" ;;')
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--stage', type=int, default=1, choices=[0, 1, 2],
                    help='0 screen (1 replicate), 1 breadth (replicates 1-9, appended to '
                         'stage 0), 2 depth (all conditions, chosen models and reps). '
                         'Default 1.')
    ap.add_argument('--replicates', type=int, default=None,
                    help='Override the replicate count for the stage. The analysis needs at '
                         'least 5 per cell (MIN_CELL_ITERS in generate_paper_figures_v2.py), '
                         'counting stage 0 and stage 1 together.')
    ap.add_argument('--start-iteration', type=int, default=None,
                    help='Override the first replicate index. Replicate seeds depend only on '
                         'this index, so runs made at different times are exchangeable.')
    ap.add_argument('--conditions', nargs='+', default=None, choices=sorted(CONDITIONS),
                    help=f'Noise conditions to run. Default for stages 0 and 1 is the four '
                         f'structurally distinct ones ({", ".join(STAGE1_CONDITIONS)}); '
                         f'stage 2 defaults to all of them.')
    ap.add_argument('--sample-size', type=int, default=10000,
                    help='Molecules per replicate (default 10000). Small values are for '
                         'smoke tests, not for results.')
    ap.add_argument('--drop-shortlisted', action='store_true',
                    help='Leave out a model the author shortlisted for the deep run before the '
                         'screen was read. Without this the generator refuses, so a shortlisted '
                         'model cannot go missing by accident.')
    ap.add_argument('--oof-folds', type=int, default=5,
                    help="Inner folds used to score the TRAINING molecules with a model "
                         "that never fitted them. Applied to every model that emits a "
                         "per-molecule uncertainty. This is what makes the QM9 run able "
                         "to answer whether uncertainty finds the corrupted labels at "
                         "all: a QM9 test label is never corrupted, so a test row has no "
                         "corruption to find. It multiplies those models' fit count by "
                         "(1 + this), which is the price of having no leakage anywhere in "
                         "the comparison (RERUN_PLAN.md 13, the validation-versus-"
                         "refitting section). 5 matches the laboratory jobs.")
    ap.add_argument('--max-hours', type=int, default=47,
                    help='Refuse to write a script that needs more wall time than this, '
                         'rather than capping the request silently. 47 is the safe default '
                         'for `medium` (limit 2 days, so a 47:59 request fits). `long` is 30 '
                         'days: pass --max-hours 720 for it. Recorded partition limits are in '
                         'RERUN_PLAN.md 2.8i. A capped request is a job that dies on the wall '
                         'clock after the queue wait, which is why this raises instead.')
    ap.add_argument('--throttle', type=int, default=5)
    ap.add_argument('--models', nargs='+', default=None, help='Subset of model labels.')
    ap.add_argument('--reps', nargs='+', default=None, choices=ALL_REPS,
                    help='Subset of representations. The Tanimoto GP is still restricted to '
                         'the binary fingerprints whatever is asked for here.')
    ap.add_argument('--include-excluded', action='store_true',
                    help='Also generate the model variants that GLOBAL_MODELS_EXCLUDE drops from '
                         'every figure (conformal wrappers, last-layer and pre-VBLL variational '
                         'BNNs, flexible DNN). They feed only the no-exclusions supplementary '
                         'table. Off by default because nothing reads the files.')
    ap.add_argument('--qsar-dir', default=QSAR_DIR,
                    help='Checkout the job cd\'s into. Defaults to the cluster path; point it '
                         'at a local checkout to smoke-test a generated script.')
    ap.add_argument('--out-dir', default=str(Path(__file__).parent))
    args = ap.parse_args()

    defaults = dict(STAGE_DEFAULTS[args.stage])
    # A pair-subset condition is NOT in the screen (it is excluded from stage 0 by
    # _ALL_PAIRS), so there is no replicate 0 for it to inherit. The main grid's defaults
    # are replicates=9 starting at 1 precisely because the screen supplies replicate 0 --
    # applying them here silently produced 9 replicates numbered 1..9, against the 10 the
    # author settled, and with indices that do not line up with the other conditions.
    # Found by the close-out audit 2026-08-27.
    if args.stage in (0, 1) and args.conditions and \
            all(c in PAIR_SUBSET_CONDITIONS for c in args.conditions):
        defaults['replicates'] = 10
        defaults['start'] = 0
    conditions = args.conditions or defaults['conditions']
    n_reps_run = args.replicates if args.replicates is not None else defaults['replicates']
    first_iter = args.start_iteration if args.start_iteration is not None else defaults['start']

    # Stage 2 is chosen models on chosen representations, and which ones cannot be
    # decided before stage 0 has run (RERUN_PLAN.md §13.1 item 4). Generating a
    # full stage-2 grid by default would quietly cost more than stages 0 and 1
    # together, for a question that is about a handful of cells.
    if args.stage == 2 and not (args.models and args.reps):
        ap.error('--stage 2 needs --models and --reps. Which models and representations go '
                 'deep is chosen from what stage 0 shows; see RERUN_PLAN.md §13.1 item 4.')

    # Models the author has already put on the deep run's shortlist, before the screen is
    # read. They can still be dropped, but only on purpose. ngboost went on it 2026-08-27:
    # it was absent from the first three-model screen and the seven-model one then showed it
    # is the LEAST accurate model on clean labels and the MOST robust under noise, winning 8
    # of 9 replicates at level 1.0 (RERUN_PLAN.md 13.15). That is the study's argument, and
    # it would have been missed.
    SHORTLISTED = {'ngboost': 'RERUN_PLAN.md 13.15 — least accurate clean, most robust under noise'}
    if args.stage == 2 and args.models:
        missing = [m for m in SHORTLISTED if m not in args.models]
        if missing and not args.drop_shortlisted:
            ap.error(
                'the deep run is missing ' + ', '.join(missing) + ', which the author put on '
                'the shortlist before the screen was read:\n  '
                + '\n  '.join(f'{m}: {SHORTLISTED[m]}' for m in missing)
                + '\nAdd it, or pass --drop-shortlisted to leave it out on purpose.')

    # A pair-subset condition may not be generated at full breadth. Without this the four
    # main-grid conditions look interchangeable and censoring would quietly cost 5,460 runs
    # instead of 350. Same shape as the stage-2 refusal above: name the choice, do not
    # invent one.
    restricted = [c for c in conditions if c in PAIR_SUBSET_CONDITIONS]
    # Scripts are named by model and run-design index only, so generating a different
    # condition set into the same directory OVERWRITES the main-grid script for those
    # models -- exit 0, no warning, and the files are untracked so git cannot restore them.
    # Found by the close-out audit 2026-08-27. A non-default condition set gets its own tag.
    if restricted and args.out_dir == str(Path(__file__).parent):
        ap.error(
            f"{', '.join(restricted)} would be written into the generator's own directory "
            f"and overwrite the main-grid scripts for the same models, which are named by "
            f"model alone. Pass --out-dir <somewhere else>.")

    if restricted and not (args.models and args.reps):
        first = PAIR_SUBSET_CONDITIONS[restricted[0]]
        ap.error(
            f"{', '.join(restricted)} runs on about {first['n_pairs']} model-and-representation "
            f"pairs on QM9, not the full grid, so it needs --models and --reps. Which pairs is "
            f"chosen from the screen; see RERUN_PLAN.md 13.13. To run the rest of the grid "
            f"without it, pass --conditions "
            f"{' '.join(c for c in STAGE1_CONDITIONS if c not in PAIR_SUBSET_CONDITIONS)}.")
    # At least N of the named models must emit a per-molecule uncertainty (author,
    # 2026-08-28). Half the roster emits none -- rf, xgboost, lgb and svm -- so a
    # five-pair selection made on robustness alone can leave censoring unable to say
    # anything about uncertainty, which is one of the two questions it is here for:
    # which molecules get clipped depends on their value, so the model can see it
    # coming. The rule lives in noise_conditions.json; this only enforces it.
    if restricted and args.models:
        need = max(int(PAIR_SUBSET_CONDITIONS[c].get('min_uncertainty_models', 0) or 0)
                   for c in restricted)
        if need:
            unc = [m for m in args.models
                   if '-u True' in MODELS.get(m, ("",))[0]]
            if len(unc) < need:
                ap.error(
                    f"{', '.join(restricted)} needs at least {need} of the named models to emit a "
                    f"per-molecule uncertainty, and --models names {len(unc)} "
                    f"({', '.join(unc) if unc else 'none'}). Models that emit one: "
                    f"{', '.join(sorted(m for m, spec in MODELS.items() if '-u True' in spec[0]))}. "
                    f"See RERUN_PLAN.md 13.13; the rule lives in {NOISE_CONDITIONS_FILE.name}.")

    if restricted and args.models and args.reps:
        n = len(args.models) * len(args.reps)
        if n > 2 * PAIR_SUBSET_CONDITIONS[restricted[0]]['n_pairs']:
            ap.error(
                f"--models x --reps is {n} pairs, and {', '.join(restricted)} is meant to run on "
                f"about {PAIR_SUBSET_CONDITIONS[restricted[0]]['n_pairs']}. If that is deliberate, "
                f"say so in RERUN_PLAN.md 13.13 first and raise n_pairs in "
                f"{NOISE_CONDITIONS_FILE.name} -- the file is where the decision lives.")

    if n_reps_run < 1:
        ap.error(f'--replicates must be at least 1, got {n_reps_run}')

    out = Path(args.out_dir)
    # --out-dir is REQUIRED for censoring (RUNBOOK 5b) and points at a directory
    # that does not exist yet, so creating it is part of honouring the flag. It
    # used to raise FileNotFoundError from write_text, several models into the
    # run, after printing a summary that made it look like it had worked.
    out.mkdir(parents=True, exist_ok=True)
    pool = dict(MODELS)
    if args.include_excluded:
        pool.update(EXCLUDED_MODELS)
    if args.models:
        unknown = [m for m in args.models if m not in pool]
        if unknown:
            ap.error(f'unknown model label(s) {unknown}. Known: {sorted(pool)}. '
                     f'(Add --include-excluded for the figure-excluded variants.)')
    chosen = {k: v for k, v in pool.items() if not args.models or k in args.models}

    # TWO NUMBERS, AND THEY ARE NOT THE SAME NUMBER.
    #
    # The conditions do NOT all run the same levels: `levels_for` strips the
    # clean level from every condition except the reference and censoring. So
    # there is a longest task and there is a total, and using the longest for
    # both over-reported the grid by 10.5% -- the screen printed 2,058 training
    # runs and wrote 1,862, the main grid printed 18,522 and wrote 16,758. Those
    # numbers go into the runbook, and the runbook is what gets read when the
    # queue is sized.
    #
    # `runs_per_task` stays the LONGEST, deliberately: one wall clock covers a
    # whole array, so it has to fit the worst task in it. Under-requesting loses
    # the job after the queue wait, which is the most expensive way this run can
    # fail. Only the reported total changes.
    n_lev = max(len(CONDITIONS[c][1].split()) for c in conditions)
    runs_per_task = n_lev * n_reps_run
    levels_by_condition = {c: len(CONDITIONS[c][1].split()) for c in conditions}
    runs_per_rep = sum(levels_by_condition.values()) * n_reps_run
    own_clean = [c for c in conditions if c in NEEDS_OWN_CLEAN_LEVEL]
    if REFERENCE_CONDITION not in conditions:
        borrowers = [c for c in conditions if c not in NEEDS_OWN_CLEAN_LEVEL]
        if borrowers:
            print(f"  note: {REFERENCE_CONDITION} is not in this set, so copy_zero_rows.py will "
                  f"have no source to copy the clean row from for {' '.join(borrowers)}.")

    written = []
    grand = 0
    grand_runs = 0
    for model, (flags, tier, hours_per_110, note, model_reps) in chosen.items():
        # EVERY MODEL THAT EMITS A PER-MOLECULE UNCERTAINTY IS CROSS-FITTED.
        # Settled by the author 2026-08-28.
        #
        # WHY THIS IS HERE AT ALL. A QM9 TEST label is never corrupted, by
        # design. These scripts passed neither this flag nor --score-validation,
        # so every uncertainty row the grid produced was a test row and the
        # question "does the uncertainty find the corrupted labels?" had no data
        # behind it -- while RERUN_PLAN.md 3.1c said QM9 could answer it.
        #
        # WHY CROSS-FITTING AND NOT THE CHEAPER VALIDATION SCORING. Scoring the
        # validation molecules costs one forward pass instead of --oof-folds
        # extra fits, and for the forests and the Gaussian processes it is
        # legitimate: they fit on the training split alone and never see a
        # validation label. It is NOT legitimate for the four neural families or
        # for NGBoost, which choose when to stop by watching the validation loss,
        # so their error there is optimistic.
        #
        # Applying it only to the models where it is clean was considered and
        # REFUSED, because it makes the model comparison meaningless: the
        # forests' numbers would come from 500 validation molecules scored by a
        # model fitted on 80% of the data, and the networks' from 4,000 training
        # molecules scored by inner models fitted on ~53%. Any difference between
        # two models would then confound the model with the route that produced
        # its number -- the same confound closed on 2026-08-27, when model
        # families had different training-set sizes and nothing on the row said
        # which regime produced it (RERUN_PLAN.md 2.12).
        #
        # One route for every model. The route with no leakage in it is this one.
        #
        # Keyed on `-u True` because that is the same test the censoring guard
        # above uses to decide which models emit an uncertainty; two different
        # answers to "does this model emit one?" is how a roster and a guard
        # drift apart.
        # WHICH PAIRS ACTUALLY GET IT. `-u True` in the roster says the model
        # CAN emit a per-molecule uncertainty, and every generate-time guard
        # above reads it that way. What the settled pairs decide is which
        # (model, representation) combinations the uncertainty pass is worth
        # spending the extra fits on, and that is a property of the pair, not of
        # the model -- the variational network is worth running on ChemBERTa and
        # on neither of the other two.
        #
        # So the flags are moved out of the literal command and into a case
        # statement on the representation the array task picked. A task on a pair
        # that is not settled trains exactly as before, writes its accuracy row,
        # and does no out-of-fold pass at all.
        reps = [r for r in model_reps if not args.reps or r in args.reps]
        if not reps:
            print(f"  skipping {model}: none of --reps {args.reps} is available to it "
                  f"(it runs on {model_reps})")
            continue

        # WHAT IS RESTRICTED, AND WHAT IS NOT.
        #
        # `-u True` STAYS on every model that can emit a per-molecule
        # uncertainty. It costs nothing -- it writes the test rows the model has
        # already produced -- and taking it away would silently stop seven models
        # emitting anything at all, which is a larger change than the pair
        # decision asked for and would empty figures that read those rows.
        #
        # `--oof-folds` is what the settled pairs restrict. It is the expensive
        # half: it refits the model once per inner fold, so a run costs
        # (1 + folds) fits instead of one. It is also the half that matters for
        # the question, because a QM9 TEST label is never corrupted -- only the
        # out-of-fold training rows can answer "is the model less certain where
        # the labels are unreliable", and those are the rows the laboratory side
        # produces for its ten pairs.
        #
        # Which representation a task has is not known until the array
        # dispatches, so the choice is a case statement rather than a flag baked
        # into the command. Filtered by the representations actually GENERATED,
        # not by the model's full list: a run made with --reps that excludes
        # every settled one must not then request the wall clock for a pass it
        # will never run.
        unc_reps = (UNCERTAINTY_PAIRS.get(model, []) if '-u True' in flags else [])
        unc_reps = [r for r in unc_reps if r in reps]
        oof_scored = OOF_FOLDS_SCORED.get(model, 0)
        if oof_scored and oof_scored > args.oof_folds:
            raise SystemExit(
                f"ERROR: OOF_FOLDS_SCORED asks {model} to score {oof_scored} of "
                f"{args.oof_folds} folds, which is more folds than are cut.")
        unc_block = build_uncertainty_block(model, unc_reps, args.oof_folds,
                                            oof_scored)
        n_tasks = len(conditions) * len(reps)
        grand += n_tasks
        # The real total: this model's representations times the levels each
        # condition actually runs, not times the longest condition's count.
        grand_runs += len(reps) * runs_per_rep
        # The hours column is quoted for 110 training runs at ONE fit per run.
        #
        # THE CROSS-FIT IS NOT FREE, AND THIS IS WHERE THAT GETS PAID FOR.
        # --oof-folds scores the training molecules with inner models that never
        # fitted them, so a model carrying it does (1 + folds) fits per training
        # run, not one. hours_per_110 was measured before that existed
        # (afd92ec) and nothing rescaled it, so for a day every model with
        # `-u True` -- 11 of the 17 -- requested a wall for one fit and would
        # have done six. The screen's ngboost tier asked 4:59 and needs about 24
        # hours; the main grid asked 34:59 and needs about 204. Those jobs queue
        # for days and are then killed by the clock, which is the most expensive
        # way this run can fail (RERUN_PLAN.md, chat H).
        #
        # The multiplier is deliberately the pessimistic (1 + folds) rather than
        # (1 + folds * (folds-1)/folds), which is what the inner fits actually
        # cost on a smaller training set. Over-requesting delays a start;
        # under-requesting loses the whole job after the queue wait.
        # Keyed on whether ANY of this script's representations is a settled
        # pair, not on the flags -- since 2026-08-29 the pass is chosen per task
        # by a case statement on the representation, so `--oof-folds` no longer
        # appears in the literal command and reading the flags would size every
        # script for one fit. One wall clock covers the whole array, so it has to
        # be the worst task in it: a task on a settled pair.
        fits_per_run = 1 + (oof_scored or args.oof_folds) if unc_reps else 1
        hours = max(1, math.ceil(
            hours_per_110 * runs_per_task * fits_per_run / 110 * 1.25))
        if hours > args.max_hours:
            raise SystemExit(
                f"ERROR: {model} needs {hours}h ({runs_per_task} training runs x "
                f"{fits_per_run} fits) but --max-hours is {args.max_hours}.\n"
                f"       medium is 2 days, long is 30 (RERUN_PLAN.md 2.8i).\n"
                f"       Either submit this tier to long with --max-hours 720, or cut "
                f"the replicate count.\n"
                f"       Silently capping the request is what would get the job killed "
                f"after days in the queue.")
        script_name = f'qm9_s{args.stage}_{model}.sh'
        (out / script_name).write_text(TEMPLATE.format(
            model=model, note=note or model, jobslug=model, stage=args.stage,
            cpus=8, mem='128G', hours=hours, flags=flags,
            qsar_dir=args.qsar_dir, sample_size=args.sample_size,
            n_reps_run=n_reps_run, first_iter=first_iter,
            last_iter=first_iter + n_reps_run - 1,
            cond_list=' '.join(conditions), cond_cases=build_case_block(conditions),
            reps=' '.join(reps),
            n_cond=len(conditions), n_rep=len(reps), n_tasks=n_tasks,
            n_lev=n_lev, runs=runs_per_task, unc_block=unc_block,
            last=n_tasks - 1, throttle=args.throttle, script_name=script_name))
        (out / script_name).chmod(0o755)
        written.append((tier, script_name, model, hours, n_tasks, len(reps)))

    print(f"Stage {args.stage}: {len(written)} array scripts, {grand} tasks total")
    print(f"  conditions: {' '.join(conditions)}")
    print(f"  replicates: {n_reps_run}, numbered {first_iter}..{first_iter + n_reps_run - 1}")
    _spread = sorted(set(levels_by_condition.values()))
    print(f"  longest task: {n_lev} levels x {n_reps_run} replicate(s) = "
          f"{runs_per_task} training runs"
          + (f" (levels per condition: "
             f"{', '.join(f'{c}={n}' for c, n in sorted(levels_by_condition.items()))})"
             if len(_spread) > 1 else ""))
    if own_clean:
        print(f"  the clean level runs under {REFERENCE_CONDITION} and under "
              f"{' '.join(own_clean)}, which needs its OWN clean row as the control for the "
              f"uncertainty question (RERUN_PLAN.md 3.1f); copy_zero_rows.py fills in the rest "
              f"and CHECKS the ones that ran")
    else:
        print(f"  the clean level runs under {REFERENCE_CONDITION} only; "
              f"copy_zero_rows.py fills in the rest afterwards")
    print(f"  grid total: {grand_runs:,} training runs")
    if args.sample_size != 10000:
        print(f"  ⚠ sample size {args.sample_size}, NOT the production 10000")
    for tier, name in [(1, 'ANOVA roster — tree and deterministic'),
                       (2, 'ANOVA roster — Bayesian networks'),
                       (3, 'outside the ANOVA but feeding figures/supplementary'),
                       (4, 'excluded from every figure — only with --include-excluded')]:
        rows = [w for w in written if w[0] == tier]
        if rows:
            print(f"\n  Tier {tier} ({name}):")
            for _, nm, m, h, nt, nr in rows:
                print(f"    {nm:36s} {m:26s} {nr} reps  {nt:3d} tasks  --time={h}:59:00")


if __name__ == '__main__':
    main()
