#!/usr/bin/env python3
"""Generate the SLURM job arrays for the QM9 re-run.

WHY EVERYTHING ABOVE ZERO NOISE HAS TO BE REDONE
------------------------------------------------
The noise map is keyed by TRAINING index, and write_data restarted its counter
for every split -- so validation and test molecules were handed the noise drawn
for the training molecule at the same position. Held-out labels were corrupted
contrary to the Methods, AND the corruption was attached to the wrong molecules.
Every QM9 R2 above zero noise was scored against a moving target.

Fixed in rust/src/main.rs (apply_noise flag, true only for the training call).
The fix is in the repo; the binary must be REBUILT on the cluster.

Results at zero noise are unaffected -- process_and_train.py switches the noise
path off for all splits at level 0. They are re-run here anyway because splicing
two runs is more error-prone than re-running one grid, and zero is 1/7th of the
cost.

WHAT CHANGED ON 2026-08-27, AND WHY THE OLD SCRIPTS COULD NOT RUN
-----------------------------------------------------------------
This generator was written against the noise scheme that has since been replaced
(NOISE_DESIGN.md). It emitted `--sigma` and `--noise-strategy`, and
process_and_train.py now refuses both BY NAME (:420-431) rather than ignoring
them, because a job written against the old scheme would otherwise run silently
under the new one where the level means something different. It also emitted
`-b` for the replicate count, and two representations -- mol2vec and one-hot
SMILES -- that were dropped from the study on 2026-08-26 and are refused by name
in parse_mmap (:1173, :1199). Every generated script would therefore have failed
at argument parsing, or in the reader.

Nothing generated by the old version is recoverable or worth recovering: the
.sh files are not in version control (SLURM scripts are copied to the cluster,
not committed), so this file IS the artefact.

WHAT A CONDITION IS NOW
-----------------------
The old six "strategies" were one strategy at six doses (RERUN_PLAN.md 2.2).
The replacement separates two things that were tangled together:

  --noise-shape      the shape of each individual draw   (gaussian, student_t, laplace)
  --noise-targeting  who gets hit and how hard           (uniform, grouped_wide,
                                                          grouped_shift, outlier, censoring)

and every combination delivers the SAME amount of noise at the same level, so
the conditions are comparable to each other. A "condition" below is one
(shape, targeting) pair plus the parameters that pair needs. The level grids
come from the range-finding run, NOISE_DESIGN.md 6.4 -- seven dose levels for
the zero-mean conditions, seven censoring fractions for censoring, which is not
zero-mean and cannot be dose-matched.

THE STAGES
----------
RERUN_PLAN.md 13.1, agreed 2026-08-26. The replicate seed depends only on the
replicate index, so stage 0 IS replicate 0 of stage 1 and is reused rather than
thrown away -- which is why --stage 1 starts at iteration 1 and why both stages
write to the same file.

  stage 0  screen     every model x every rep, the stage-1 conditions, 1 replicate
  stage 1  breadth    the same grid, replicates 1-9 appended to stage 0's
  stage 2  depth      chosen models x chosen reps, ALL conditions, 10 replicates

Stage 2 cannot be generated blind -- which models and representations go deep is
open (13.1 item 4) and cannot be chosen before stage 0 has run -- so --stage 2
requires --models and --reps explicitly.

THE GRID
--------
13 models x 6 representations x {conditions} x 7 levels x {replicates}.
Model and representation are the two factors of the variance decomposition, so
neither can be cut without gutting the paper's first question.

One array TASK per (condition, representation); one SCRIPT per model.
"""
import argparse
import json
import math
from pathlib import Path

# ---------------------------------------------------------------------------
# Representations
# ---------------------------------------------------------------------------
# The set was settled on 2026-08-26 and is enforced in the code: PDV
# (continuous_pdv), MHG-GNN, Avalon, ECFP4, ChemBERTa, Sort & Slice. mol2vec is
# deleted outright; one-hot SMILES and randomized SMILES still build but are
# refused by name in process_and_train.py parse_mmap, so a job that asked for
# them would raise rather than produce results with nowhere to go.
#
#   ALL_REPS  the six.
#   FP_REPS   binary fingerprints only. The Tanimoto kernel is defined on binary
#             vectors, so the Tanimoto GP can only run here.
ALL_REPS = ['ecfp4', 'continuous_pdv', 'mhggnn', 'avalon', 'chemberta', 'sns']
FP_REPS = ['ecfp4', 'sns']

# ---------------------------------------------------------------------------
# Noise conditions
# ---------------------------------------------------------------------------
# Level grids, NOISE_DESIGN.md 6.4, both set by the range-finding run (5.5).
# Below 0.2 of the label spread the models are indistinguishable from clean;
# 1.5 is kept because it is the only level where the conditions separate at all.
DOSE_LEVELS = '0.0 0.2 0.3 0.5 0.75 1.0 1.5'
# Censoring is swept on its own axis -- the fraction of labels clipped at the
# assay limit. There is no knee; damage accelerates smoothly, becoming serious
# around 20% and severe past 30%.
CENSOR_LEVELS = '0.0 0.10 0.20 0.25 0.30 0.40 0.50'

# WHICH CONDITIONS EXIST, AND WHICH RUN AT FULL GRID, IS NOT DECIDED HERE.
#
# noise_conditions.json is the settled set, and it is read by tests on both
# injectors. This generator reads it too, rather than restating it: a restatement
# is how the two injectors drifted apart for the life of the project, and a job
# script that runs a condition the study does not recognise is the same failure
# one layer up.
#
# What DOES belong here is the translation from a condition name to the
# command-line flags that produce it, and which level grid it is swept on. That
# is the generator's actual job.
#
# Only flags that DIFFER from the process_and_train.py default are passed. The
# rest are echoed in full by the injector on every call (the "Rust command:" line
# in the job output), so provenance is captured without this file restating --
# and eventually contradicting -- the defaults. The single-setting decisions
# (nu, the outlier fraction, which end censoring clips) come from the settled
# file, spelled out on the command line so the job log records them.
NOISE_CONDITIONS_FILE = Path(__file__).resolve().parent.parent / 'noise_conditions.json'
_SETTLED = json.loads(NOISE_CONDITIONS_FILE.read_text())
_SETTINGS = _SETTLED['settings_that_follow']

CONDITION_FLAGS = {
    'gaussian':        ('--noise-shape gaussian --noise-targeting uniform', DOSE_LEVELS),
    'grouped_wider':   ('--noise-shape gaussian --noise-targeting grouped_wide', DOSE_LEVELS),
    'grouped_shifted': ('--noise-shape gaussian --noise-targeting grouped_shift', DOSE_LEVELS),
    'censoring':       (f"--noise-targeting censoring "
                        f"--censor-side {_SETTINGS['censor_side']}", CENSOR_LEVELS),
    'student_t_nu5':   (f"--noise-shape student_t --noise-targeting uniform "
                        f"--nu {_SETTINGS['nu']}", DOSE_LEVELS),
    'outlier_p10':     (f"--noise-shape gaussian --noise-targeting outlier "
                        f"--outlier-p {_SETTINGS['outlier_p']}", DOSE_LEVELS),
    'laplace':         ('--noise-shape laplace --noise-targeting uniform', DOSE_LEVELS),
}

# The clean level is run ONCE, under the reference condition, and copied into the
# others by copy_zero_rows.py after the array finishes.
#
# At level 0 the pipeline does not add noise at all -- it switches the noise step
# off for every split -- and the replicate seed depends only on the replicate
# number, so the clean run is bit-identical whichever condition it is labelled
# with. Measured on 400 QM9 molecules with the random forest on ECFP4: all four
# conditions returned R2 = 0.7579128047581825 and RMSE = 0.5176004014184159, to
# the last digit.
#
# Running it four times costs 11% of the QM9 grid to recompute a number we
# already have. It cannot simply be dropped, because auc_norm divides each
# condition's curve by that condition's OWN clean accuracy, so a condition with
# no clean row has nothing to divide by -- hence the copy.
REFERENCE_CONDITION = 'gaussian'


def levels_for(name, levels):
    """The levels a condition actually runs. Only the reference runs the clean one."""
    if name == REFERENCE_CONDITION:
        return levels
    return ' '.join(v for v in levels.split() if float(v) != 0.0)


STAGE1_CONDITIONS = [c['name'] for c in _SETTLED['stage_1_full_grid']]
STAGE2_CONDITIONS = STAGE1_CONDITIONS + [c['name'] for c in _SETTLED['stage_2_depth_only']]

# name -> (flags, level grid, runs at full grid in stage 1, why -- the settled
# file's own words, so the job script header carries the reason with it)
CONDITIONS = {}
for _group in ('stage_1_full_grid', 'stage_2_depth_only'):
    for _entry in _SETTLED[_group]:
        _name = _entry['name']
        if _name not in CONDITION_FLAGS:
            raise SystemExit(
                f"{NOISE_CONDITIONS_FILE.name} names the condition '{_name}' but this generator "
                f"does not know how to ask for it. Add it to CONDITION_FLAGS, or the study runs "
                f"a set the job scripts cannot produce.")
        _flags, _levels = CONDITION_FLAGS[_name]
        CONDITIONS[_name] = (_flags, levels_for(_name, _levels),
                             _group == 'stage_1_full_grid', _entry['why'])

_unused = sorted(set(CONDITION_FLAGS) - set(CONDITIONS))
if _unused:
    raise SystemExit(
        f"this generator can emit condition(s) {_unused} that {NOISE_CONDITIONS_FILE.name} does "
        f"not run. Either add them there with their evidence, or take them out of "
        f"CONDITION_FLAGS -- a condition nobody decided to run is how an unjustified cell gets "
        f"into the study.")

# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------
# label -> (extra CLI flags, tier, hours per 110 training runs, note, reps)
# The label is the filename suffix and MUST match what the figure script parses:
# generate_paper_figures_v2.py:592-615 maps '<base>_bnn_full_variational' to the
# VBLL models, so that spelling is load-bearing. It is also checked against
# check_environment.py QM9_MODELS by `check_environment.py --audit-roster`.
#
# The hours column is quoted PER 110 TRAINING RUNS, which is what the old
# eleven-level ten-replicate design asked of each task. The actual grid is
# smaller now and varies by stage, so the wall clock is scaled from it below
# rather than carried as a fixed number that would silently over-request.
MODELS = {
    'rf':                       ('-m rf',        1, 23, 'random forest', ALL_REPS),
    'xgboost':                  ('-m xgboost',   1, 23, '', ALL_REPS),
    'lgb':                      ('-m lgb',       1, 23, 'LightGBM', ALL_REPS),
    'svm':                      ('-m svm',       1, 35, 'RBF kernel on every representation', ALL_REPS),
    'ngboost':                  ('-m ngboost -u True', 1, 47, 'slowest tree model; emits per-molecule uncertainty', ALL_REPS),
    'dnn':                      ('-m dnn',       1, 35, '', ALL_REPS),
    'mlp':                      ('-m mlp',       1, 35, '', ALL_REPS),
    'dnn_bnn_full':             ('-m dnn --bayesian-transformation full -u True', 2, 47, 'BNN-alpha', ALL_REPS),
    'mlp_bnn_full':             ('-m mlp --bayesian-transformation full -u True', 2, 47, 'BNN-beta', ALL_REPS),
    'dnn_bnn_full_variational': ('-m dnn --bayesian-transformation full_variational -u True', 2, 47, 'VBLL-alpha (figure script reads this as dnn_vbll)', ALL_REPS),
    'mlp_bnn_full_variational': ('-m mlp --bayesian-transformation full_variational -u True', 2, 47, 'VBLL-beta (figure script reads this as mlp_vbll)', ALL_REPS),
    # Outside the ANOVA roster, but they feed figures and supplementary tables:
    'qrf':        ('-m qrf -u True', 3, 23, 'not in the ANOVA (rho 0.996 with rf) but the best error-ranker', ALL_REPS),
    'gauche_rbf': ('-m gauche --kernel rbf -u True', 3, 47, 'RBF GP on EVERY rep, so the GP can finally enter the cross-rep ANOVA', ALL_REPS),
    'gauche':     ('-m gauche --kernel tanimoto -u True', 3, 47,
                   'Tanimoto GP. Only defined on BINARY fingerprints, so ecfp4/sns only. '
                   'This is the RBF-vs-Tanimoto head-to-head; the figure script gives it its '
                   'own colour and marker and labels it GP', FP_REPS),
}

# Excluded from EVERY figure by GLOBAL_MODELS_EXCLUDE, so re-running them
# produces files nothing reads. They survive only in
# table1_supp_simple_effects_all_reps.csv, which runs with no exclusions.
# Off by default; --include-excluded turns them on.
EXCLUDED_MODELS = {
    'conformal_rf':             ('-m conformal --cp-base-model rf -u True',  4, 35, 'conformal wrapper (rho > 0.99 with rf)', ALL_REPS),
    'conformal_qrf':            ('-m conformal --cp-base-model qrf -u True', 4, 35, 'conformal wrapper', ALL_REPS),
    'conformal_dnn':            ('-m conformal --cp-base-model dnn -u True', 4, 47, 'conformal wrapper', ALL_REPS),
    # `last` matched no branch in models.py, which tests `last_layer`. The value
    # fell through, no Bayesian layer was applied, and the deterministic network
    # that resulted was put through 100 forward passes in eval mode -- all
    # identical, uncertainty exactly zero, written to a file the figure script
    # reads as a last-layer BNN. process_and_train.py now refuses an
    # unrecognised value by name, so these two would not start at all.
    'dnn_bnn_last':             ('-m dnn --bayesian-transformation last_layer -u True', 4, 47, 'last-layer BNN (no significant gain over base)', ALL_REPS),
    'mlp_bnn_last':             ('-m mlp --bayesian-transformation last_layer -u True', 4, 47, 'last-layer BNN', ALL_REPS),
    'dnn_bnn_variational':      ('-m dnn --bayesian-transformation variational -u True', 4, 47, 'pre-VBLL variational (was identical to last-layer, a bug)', ALL_REPS),
    'mlp_bnn_variational':      ('-m mlp --bayesian-transformation variational -u True', 4, 47, 'pre-VBLL variational', ALL_REPS),
    'flexible_dnn':             ('-m flexible_dnn', 4, 35, 'architecture variant, not discussed in the paper', ALL_REPS),
}

QSAR_DIR = '/data/stat-cadd/scat9264/qsar_qm_models'

TEMPLATE = '''#!/bin/bash
# ============================================================================
# QM9 re-run — stage {stage} — model: {model}
# {note}
# ============================================================================
# Array task -> (noise condition, representation).
#   {n_cond} conditions x {n_rep} representations = {n_tasks} tasks
#   each task = {n_lev} noise levels x {n_reps_run} replicate(s) = {runs} training runs
#
# Conditions in this stage: {cond_list}
# Replicates: {n_reps_run}, numbered {first_iter}..{last_iter}. The replicate seed
# depends only on the replicate index, so these are exchangeable with a run made
# at any other time and append to the same file.
#
# REQUIRES the rebuilt rust binary (the held-out-noise fix). Run
# `cargo build --release` in {qsar_dir}/rust FIRST -- see RUNBOOK.
#
# --account and --partition are LIVE STATE; pass them at submit time:
#   sbatch --account=<acct> --partition=medium --array=0-{last}%{throttle} {script_name}
#
# Resubmit only failed indices:
#   sbatch --account=<acct> --partition=medium --array=3,17 {script_name}
# ============================================================================
#SBATCH --job-name=qm9{stage}_{jobslug}
#SBATCH --output=qm9{stage}_{jobslug}_%A_%a.out
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
#SBATCH --time={hours}:59:00
#SBATCH --mail-user=adelaide.punt@stcatz.ox.ac.uk
#SBATCH --mail-type=FAIL

set -uo pipefail

# micromamba has never worked on this cluster -- setup.sh has always fallen
# through to its conda branch. The two `export MAMBA_EXE=...` lines that used to
# sit here were dead: the hook failed, and because this script runs under
# `set -uo pipefail` with no `-e`, the failure did not stop anything. The task
# simply carried on unactivated, in whatever python was on PATH.
cd {qsar_dir}
. setup.sh

# Activation is not optional, and until now nothing checked it. An unactivated
# task falls through to the system Anaconda at /apps/system/..., which has no
# gpytorch, no quantile_forest and no ngboost -- so the job runs, finds nothing
# to do, and produces no rows. That is what happened to 12822693 and 12822694
# (RERUN_PLAN.md §2.8d). Confirmed on the cluster 2026-08-26.
if [ -z "${{CONDA_PREFIX:-}}" ]; then
    echo "ERROR: setup.sh did not activate an environment (CONDA_PREFIX unset)."
    exit 2
fi
PY_PATH="$(command -v python)"
case "$PY_PATH" in
    "$CONDA_PREFIX"/*) : ;;
    *)
        echo "ERROR: python is $PY_PATH, which is not inside the activated"
        echo "       environment ($CONDA_PREFIX)."
        case "$PY_PATH" in
            /apps/system/*)
                echo "       That is the system Anaconda. It has no gpytorch, no"
                echo "       quantile_forest and no ngboost, so this job would run,"
                echo "       find nothing to do, and write no rows." ;;
        esac
        exit 2 ;;
esac
# The test above cannot fail once setup.sh has run: setup.sh:124 prepends
# $CONDA_PREFIX/bin to PATH, so python resolves inside the prefix whichever
# environment was activated. It still catches an unset CONDA_PREFIX, which is
# the case that actually bit us -- but on its own it would pass a task that
# activated the WRONG environment, so the name is checked too. This literal
# must track ENV_NAME in setup.sh.
if [ "$(basename "$CONDA_PREFIX")" != "env_test" ]; then
    echo "ERROR: the active environment is $(basename "$CONDA_PREFIX"), not env_test"
    echo "       (CONDA_PREFIX=$CONDA_PREFIX). setup.sh activated the wrong one."
    exit 2
fi
echo "=== interpreter: $PY_PATH  (CONDA_PREFIX=$CONDA_PREFIX)"

# A private scratch directory per task.
#
# Hygiene, not a fix for any known defect here: joblib, matplotlib, numba and
# the HuggingFace cache all honour TMPDIR, and a fixed-name temp file shared by
# concurrent array tasks is the defect class that produced the config.json race.
# This closes the whole class cheaply.
#
# It does NOT fix the one instance found while testing: keopscore (gpytorch ->
# pykeops) hardcodes /tmp/compiler_version.txt and /tmp/brew_prefix.txt, writing
# and deleting them during import, so two simultaneous imports race and one dies
# with FileNotFoundError. TMPDIR is ignored by that code. It is guarded by
# platform.system() == "Darwin", so it cannot fire on this cluster -- it is a
# macOS-only problem, and it is why the two-task half of
# scripts/test_config_isolation.py skips on a laptop.
export TMPDIR="${{TMPDIR:-/tmp}}/qsar_${{SLURM_JOB_ID:-$$}}_${{SLURM_ARRAY_TASK_ID:-0}}"
mkdir -p "$TMPDIR"
trap 'rm -rf "$TMPDIR"' EXIT


# The binary carries the held-out-noise fix. Refuse to run without it rather
# than silently regenerating the same invalid results.
if [ ! -x rust/target/release/rust_processor ]; then
    echo "ERROR: rust/target/release/rust_processor missing. Run:"
    echo "  cd {qsar_dir}/rust && cargo build --release"
    exit 2
fi

cd scripts

# The interpreter has to be able to BUILD what this job is about to ask for.
# Jobs 12822693 and 12822694 (2026-08-19) ran to completion and produced nothing
# because gpytorch was missing: the experiment list came out empty, five folds
# looped over nothing, and the job crashed reading its own empty output. This
# costs seconds and answers that before the queue does (RERUN_PLAN.md §2.8d).
python check_environment.py --models {model} || {{
    echo "ERROR: this interpreter cannot build model '{model}'. See the output above."
    exit 2
}}

CONDS=({cond_list})
REPS=({reps})

n_rep=${{#REPS[@]}}
n_tasks=$(( ${{#CONDS[@]}} * n_rep ))
i="${{SLURM_ARRAY_TASK_ID:-0}}"
if [ -z "${{SLURM_ARRAY_TASK_ID:-}}" ]; then
    echo "WARNING: not an array job — running task 0 only. Submit with --array=0-$(( n_tasks - 1 ))%N"
fi
if [ "$i" -ge "$n_tasks" ]; then
    echo "ERROR: task $i is out of range (0..$(( n_tasks - 1 )))"; exit 2
fi
if [ -z "${{SLURM_JOB_PARTITION:-}}" ]; then
    echo "ERROR: no partition. Submit with --partition=medium (see RUNBOOK)."; exit 2
fi

rep="${{REPS[$(( i % n_rep ))]}}"
cond="${{CONDS[$(( i / n_rep ))]}}"

# Each condition is a (shape, targeting) pair plus whatever that pair needs, and
# its own level grid -- censoring is a fraction of labels clipped, not a dose, so
# it cannot share the others' axis. Only flags that differ from the
# process_and_train.py default are passed; the injector echoes the full parameter
# set on every call, so the run log carries the provenance.
#
# A case statement rather than an associative array: associative arrays need
# bash 4, and this file is also smoke-tested on macOS, where /bin/bash is 3.2.
case "$cond" in
{cond_cases}
  *) echo "ERROR: unknown noise condition '$cond'"; exit 2 ;;
esac

OUT="../results/anova_${{cond}}_${{rep}}_{model}.csv"

echo "=== task $i: model={model} condition=$cond rep=$rep"
echo "=== noise: $NOISE_FLAGS"
echo "=== levels: $LEVELS"
echo "=== replicates: {n_reps_run} starting at {first_iter}"
echo "=== out: $OUT"
echo "=== started: $(date)"

python -u process_and_train.py -d QM9 -t homo_lumo_gap \\
    {flags} \\
    -r "$rep" \\
    --noise-level $LEVELS \\
    --dose-units spread \\
    $NOISE_FLAGS \\
    -n {sample_size} \\
    --repetitions {n_reps_run} \\
    --start-iteration {first_iter} \\
    -s scaffold \\
    --normalize True \\
    -f "$OUT"

status=$?
echo "=== finished: $(date)  exit=$status"
exit $status
'''


# Stage defaults, RERUN_PLAN.md §13.1. Stage 0 is replicate 0 of stage 1, so
# stage 1 starts at iteration 1 and both write to the same file.
STAGE_DEFAULTS = {
    0: dict(replicates=1,  start=0, conditions=STAGE1_CONDITIONS),
    1: dict(replicates=9,  start=1, conditions=STAGE1_CONDITIONS),
    2: dict(replicates=10, start=0, conditions=STAGE2_CONDITIONS),
}


def build_case_block(tags):
    """The bash case statement that turns a condition tag into flags and levels."""
    lines = []
    for tag in tags:
        flags, levels, _, why = CONDITIONS[tag]
        lines.append(f'  # {why}')
        lines.append(f'  {tag}) NOISE_FLAGS="{flags}"; LEVELS="{levels}" ;;')
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--stage', type=int, default=1, choices=[0, 1, 2],
                    help='0 screen (1 replicate), 1 breadth (replicates 1-9, appended to '
                         'stage 0), 2 depth (all conditions, chosen models and reps). '
                         'Default 1.')
    ap.add_argument('--replicates', type=int, default=None,
                    help='Override the replicate count for the stage. The analysis needs at '
                         'least 5 per cell (MIN_CELL_ITERS in generate_paper_figures_v2.py), '
                         'counting stage 0 and stage 1 together.')
    ap.add_argument('--start-iteration', type=int, default=None,
                    help='Override the first replicate index. Replicate seeds depend only on '
                         'this index, so runs made at different times are exchangeable.')
    ap.add_argument('--conditions', nargs='+', default=None, choices=sorted(CONDITIONS),
                    help=f'Noise conditions to run. Default for stages 0 and 1 is the four '
                         f'structurally distinct ones ({", ".join(STAGE1_CONDITIONS)}); '
                         f'stage 2 defaults to all of them.')
    ap.add_argument('--sample-size', type=int, default=10000,
                    help='Molecules per replicate (default 10000). Small values are for '
                         'smoke tests, not for results.')
    ap.add_argument('--throttle', type=int, default=5)
    ap.add_argument('--models', nargs='+', default=None, help='Subset of model labels.')
    ap.add_argument('--reps', nargs='+', default=None, choices=ALL_REPS,
                    help='Subset of representations. The Tanimoto GP is still restricted to '
                         'the binary fingerprints whatever is asked for here.')
    ap.add_argument('--include-excluded', action='store_true',
                    help='Also generate the model variants that GLOBAL_MODELS_EXCLUDE drops from '
                         'every figure (conformal wrappers, last-layer and pre-VBLL variational '
                         'BNNs, flexible DNN). They feed only the no-exclusions supplementary '
                         'table. Off by default because nothing reads the files.')
    ap.add_argument('--qsar-dir', default=QSAR_DIR,
                    help='Checkout the job cd\'s into. Defaults to the cluster path; point it '
                         'at a local checkout to smoke-test a generated script.')
    ap.add_argument('--out-dir', default=str(Path(__file__).parent))
    args = ap.parse_args()

    defaults = STAGE_DEFAULTS[args.stage]
    conditions = args.conditions or defaults['conditions']
    n_reps_run = args.replicates if args.replicates is not None else defaults['replicates']
    first_iter = args.start_iteration if args.start_iteration is not None else defaults['start']

    # Stage 2 is chosen models on chosen representations, and which ones cannot be
    # decided before stage 0 has run (RERUN_PLAN.md §13.1 item 4). Generating a
    # full stage-2 grid by default would quietly cost more than stages 0 and 1
    # together, for a question that is about a handful of cells.
    if args.stage == 2 and not (args.models and args.reps):
        ap.error('--stage 2 needs --models and --reps. Which models and representations go '
                 'deep is chosen from what stage 0 shows; see RERUN_PLAN.md §13.1 item 4.')

    if n_reps_run < 1:
        ap.error(f'--replicates must be at least 1, got {n_reps_run}')

    out = Path(args.out_dir)
    pool = dict(MODELS)
    if args.include_excluded:
        pool.update(EXCLUDED_MODELS)
    if args.models:
        unknown = [m for m in args.models if m not in pool]
        if unknown:
            ap.error(f'unknown model label(s) {unknown}. Known: {sorted(pool)}. '
                     f'(Add --include-excluded for the figure-excluded variants.)')
    chosen = {k: v for k, v in pool.items() if not args.models or k in args.models}

    # Every condition on the grid has the same number of levels, and the wall
    # clock is priced per training run, so one number covers the whole script.
    # The reference condition runs one level more than the others -- the clean one.
    # The wall clock is requested for the longest, so no task is short of time.
    n_lev = max(len(CONDITIONS[c][1].split()) for c in conditions)
    runs_per_task = n_lev * n_reps_run
    if REFERENCE_CONDITION not in conditions:
        print(f"  note: {REFERENCE_CONDITION} is not in this set, so nothing here runs the clean "
              f"level and copy_zero_rows.py will have no source to copy from.")

    written = []
    grand = 0
    for model, (flags, tier, hours_per_110, note, model_reps) in chosen.items():
        reps = [r for r in model_reps if not args.reps or r in args.reps]
        if not reps:
            print(f"  skipping {model}: none of --reps {args.reps} is available to it "
                  f"(it runs on {model_reps})")
            continue
        n_tasks = len(conditions) * len(reps)
        grand += n_tasks
        # The hours column is quoted for 110 training runs; scale it to what this
        # stage actually asks for, keep a 25% margin, and stay inside the 47-hour
        # partition limit.
        hours = max(1, min(47, math.ceil(hours_per_110 * runs_per_task / 110 * 1.25)))
        script_name = f'qm9_s{args.stage}_{model}.sh'
        (out / script_name).write_text(TEMPLATE.format(
            model=model, note=note or model, jobslug=model, stage=args.stage,
            cpus=8, mem='128G', hours=hours, flags=flags,
            qsar_dir=args.qsar_dir, sample_size=args.sample_size,
            n_reps_run=n_reps_run, first_iter=first_iter,
            last_iter=first_iter + n_reps_run - 1,
            cond_list=' '.join(conditions), cond_cases=build_case_block(conditions),
            reps=' '.join(reps),
            n_cond=len(conditions), n_rep=len(reps), n_tasks=n_tasks,
            n_lev=n_lev, runs=runs_per_task,
            last=n_tasks - 1, throttle=args.throttle, script_name=script_name))
        (out / script_name).chmod(0o755)
        written.append((tier, script_name, model, hours, n_tasks, len(reps)))

    print(f"Stage {args.stage}: {len(written)} array scripts, {grand} tasks total")
    print(f"  conditions: {' '.join(conditions)}")
    print(f"  replicates: {n_reps_run}, numbered {first_iter}..{first_iter + n_reps_run - 1}")
    print(f"  each task: up to {n_lev} levels x {n_reps_run} replicate(s) = "
          f"{runs_per_task} training runs")
    print(f"  the clean level runs under {REFERENCE_CONDITION} only; "
          f"copy_zero_rows.py fills in the rest afterwards")
    print(f"  grid total: {grand * runs_per_task:,} training runs")
    if args.sample_size != 10000:
        print(f"  ⚠ sample size {args.sample_size}, NOT the production 10000")
    for tier, name in [(1, 'ANOVA roster — tree and deterministic'),
                       (2, 'ANOVA roster — Bayesian networks'),
                       (3, 'outside the ANOVA but feeding figures/supplementary'),
                       (4, 'excluded from every figure — only with --include-excluded')]:
        rows = [w for w in written if w[0] == tier]
        if rows:
            print(f"\n  Tier {tier} ({name}):")
            for _, nm, m, h, nt, nr in rows:
                print(f"    {nm:36s} {m:26s} {nr} reps  {nt:3d} tasks  --time={h}:59:00")


if __name__ == '__main__':
    main()
