#!/usr/bin/env python3
"""Assemble additional_files.tex from supplementary/INDEX.md and supplementary/items/.

    python3 scripts/build_additional_files.py            # write additional_files.tex
    python3 scripts/build_additional_files.py --check    # exit 1 if it is out of date

additional_files.tex is GENERATED. Edit an item in supplementary/items/, the
order or numbering in supplementary/INDEX.md, or the preamble in
supplementary/preamble.tex, then re-run this. The rules are in
supplementary/README.md.

What the build does:
  - reads the index table, keeps the rows with a number in the "Paper file"
    column, and groups them by that number;
  - writes supplementary/preamble.tex, then one Additional file per number:
    a "% Additional file N -- title" comment (scripts/stage_additional_files.py
    reads it), a heading, \\renewcommand{\\SuppFile}{Additional file N,} so each
    caption prints its number, then each item's text;
  - inlines any \\input{...} inside an item, relative to the repository root,
    so the output is one self-contained file that compiles in Overleaf.

It refuses to build when a numbered row has no item file, when an item file is
not in the index, or when a name appears twice.
"""
import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SUPP = os.path.join(ROOT, 'supplementary')
INDEX = os.path.join(SUPP, 'INDEX.md')
ITEMS = os.path.join(SUPP, 'items')
PREAMBLE = os.path.join(SUPP, 'preamble.tex')
OUT = os.path.join(ROOT, 'additional_files.tex')

INPUT = re.compile(r'\\input\{([^}]+)\}')

HEADER = r"""%==============================================================================
% additional_files.tex -- GENERATED by scripts/build_additional_files.py.
% DO NOT EDIT THIS FILE. Edit supplementary/items/<name>.tex, the order and
% numbers in supplementary/INDEX.md, or supplementary/preamble.tex, and rebuild.
% Rules: supplementary/README.md.
%
% Compile separately from paper.tex (twice, for the longtables), then split the
% PDF into one file per Additional file for upload.
%==============================================================================
"""


def read_index():
    rows, header = [], None
    for line in open(INDEX, encoding='utf-8'):
        line = line.strip()
        if not line.startswith('|'):
            continue
        cells = [c.strip() for c in line.strip('|').split('|')]
        if header is None:
            header = [c.lower() for c in cells]
            continue
        if set(''.join(cells)) <= set('-: '):
            continue
        rows.append(dict(zip(header, cells)))
    for col in ('name', 'title', 'paper file', 'status'):
        if header is None or col not in header:
            sys.exit(f'{INDEX}: the table has no "{col}" column')
    return rows


def inline_inputs(text, seen=()):
    def sub(m):
        rel = m.group(1)
        path = os.path.join(ROOT, rel if rel.endswith('.tex') else rel + '.tex')
        if not os.path.exists(path):
            sys.exit(f'\\input{{{rel}}} points at {path}, which does not exist')
        if path in seen:
            sys.exit(f'\\input loop at {path}')
        body = open(path, encoding='utf-8').read()
        return (f'% --- inlined from {os.path.relpath(path, ROOT)} ---\n'
                + inline_inputs(body, seen + (path,)).rstrip() + '\n'
                + f'% --- end of {os.path.relpath(path, ROOT)} ---')
    return INPUT.sub(sub, text)


def build():
    rows = read_index()
    names = [r['name'] for r in rows]
    dupes = sorted({n for n in names if names.count(n) > 1})
    if dupes:
        sys.exit(f'names listed twice in the index: {", ".join(dupes)}')
    on_disk = {f[:-4] for f in os.listdir(ITEMS) if f.endswith('.tex')}
    unindexed = sorted(on_disk - set(names))
    if unindexed:
        sys.exit(f'item files not in the index: {", ".join(unindexed)}')

    groups = {}
    for r in rows:
        number = r['paper file']
        if number in ('', '—', '-'):
            continue
        if not number.isdigit():
            sys.exit(f'{r["name"]}: "Paper file" must be a whole number or —, not {number!r}')
        if r['name'] not in on_disk:
            sys.exit(f'{r["name"]} is numbered {number} but items/{r["name"]}.tex does not exist')
        groups.setdefault(int(number), []).append(r)
    expected = list(range(1, len(groups) + 1))
    if sorted(groups) != expected:
        sys.exit(f'Paper file numbers must run 1..{len(groups)} with no gaps; '
                 f'the index has {sorted(groups)}')

    parts = [HEADER, open(PREAMBLE, encoding='utf-8').read().rstrip(), '', r'\begin{document}', '']
    for number in expected:
        members = groups[number]
        title = '; '.join(r['title'] for r in members)
        parts += ['%' + '=' * 78,
                  f'% Additional file {number} \u2014 {title}',
                  f'% Items: {", ".join(r["name"] for r in members)}',
                  '%' + '=' * 78, '',
                  r'\renewcommand{\SuppFile}{Additional file ' + str(number) + ',}']
        for k, r in enumerate(members):
            heading = f'Additional file {number}' + (', continued' if k else '')
            body = open(os.path.join(ITEMS, r['name'] + '.tex'), encoding='utf-8').read()
            parts += ['', r'\begin{center}\Large\textbf{' + heading + r'}\end{center}', '',
                      inline_inputs(body).rstrip(), '', r'\newpage', '']
    parts += [r'\end{document}', '']
    return '\n'.join(parts), groups


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--check', action='store_true',
                    help='do not write; exit 1 if additional_files.tex differs from a fresh build')
    args = ap.parse_args()
    text, groups = build()
    old = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    if args.check:
        if text != old:
            print('additional_files.tex is out of date: run python3 scripts/build_additional_files.py')
            return 1
        print('additional_files.tex matches the index and the items')
        return 0
    if text == old:
        print('additional_files.tex already up to date')
        return 0
    open(OUT, 'w', encoding='utf-8').write(text)
    print(f'wrote {OUT}: {len(groups)} Additional files, '
          f'{sum(len(v) for v in groups.values())} items')
    return 0


if __name__ == '__main__':
    sys.exit(main())
