#!/usr/bin/env python
"""The paper's tables. Seven slots, CSV and LaTeX from one place.

RERUN_PLAN.md 14.7.

  T1  Metrics summary                        Methods
  T2  Noise conditions                       Methods
  T3  Variance decomposition, with spread    Q1
  T4  AUC_norm by model and condition        Q2/Q3
  T5  Probabilistic transformations          Aim 2
  T6  Uncertainty                            Q4/Q5/Q6
  T7  Rank transfer, QM9 against the assays  new

TWO JOURNAL RULES THAT SHAPE EVERY ONE OF THEM
----------------------------------------------
Journal of Cheminformatics tables carry NO COLOUR AND NO SHADING, so emphasis is
bold text or nothing -- a heat-mapped table is a figure and has to be one.

And a rule of this study rather than the journal's: **no table gets a "Mean"
column across noise conditions**. A mean over conditions is an average over a
factor, and it is the column the submitted paper sorted its ranking table by.
`assert_no_mean_column` refuses one.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

import figlib_config as C  # noqa: E402
import figlib_guard as G  # noqa: E402

#: Column names that would be an average over a factor.
_BANNED = ('mean', 'average', 'avg', 'overall', 'across')


def assert_no_mean_column(table, where):
    """A mean across noise conditions describes none of them.

    RERUN_PLAN.md 14.7 T4: "NO 'Mean' column -- a mean across noise types is
    averaging over a factor". The submitted paper's ranking table is sorted by
    exactly that column.
    """
    bad = [c for c in table.columns
           if any(b in str(c).lower() for b in _BANNED)
           and 'replicate' not in str(c).lower()]
    if bad:
        raise G.GuardError(
            f'{where}: {bad} averages over a factor. A mean across noise '
            f'conditions describes none of them, and it is the column the '
            f'submitted paper sorted its ranking by (RERUN_PLAN.md 14.7).')
    return table


def write(table, output_dir, name, caption='', where=None, index=False,
          float_format='%.3f'):
    """One table, as CSV and as a LaTeX fragment.

    The LaTeX is booktabs and carries no colour, because the journal's tables
    have none. It is a fragment, not a float: the caption and the label belong
    in the manuscript where they can be edited.
    """
    where = where or name
    assert_no_mean_column(table, where)
    G.with_components(table, where)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    table.to_csv(output_dir / f'{name}.csv', index=index)
    try:
        body = table.to_latex(index=index, escape=False, float_format=float_format,
                              column_format='l' + 'c' * (len(table.columns) - 1))
    except Exception:                                          # pragma: no cover
        body = ''
    if body:
        header = (f'% {name}. {caption}\n'
                  f'% Generated by scripts/run_paper_analysis.py; do not edit.\n'
                  f'% No colour or shading: Journal of Cheminformatics tables '
                  f'have none.\n')
        (output_dir / f'{name}.tex').write_text(header + body)
    print(f'    {name}: {len(table)} row(s)')
    return table


# ---------------------------------------------------------------------------
# T1 -- the metrics
# ---------------------------------------------------------------------------

def t1_metrics(output_dir):
    """Every metric the study reports, from the one place they are registered.

    Generated from figlib_config.METRICS rather than typed, so a metric cannot
    appear in a table under a name nothing computes -- which is failure mode 12,
    and how a retired metric survived in the Conclusion as the headline.
    """
    rows = [{'Metric': label, 'Definition': definition}
            for column, (label, definition) in sorted(C.METRICS.items(),
                                                      key=lambda kv: kv[1][0])]
    table = pd.DataFrame(rows)
    return write(table, output_dir, 'T1_metrics',
                 'Metrics used in this study. Generated from the registry the '
                 'figure code reads, so a caption cannot name a metric nothing '
                 'computes.')


# ---------------------------------------------------------------------------
# T2 -- the noise conditions
# ---------------------------------------------------------------------------

def t2_conditions(output_dir):
    """One row per settled condition: what it does to a label and why it is run.

    Read from noise_conditions.json, the file both injectors' tests read. The
    old Methods figure held its own copy of six conditions, all retired, and
    drew seven panels of no noise at all.
    """
    settled = C._SETTLED
    rows = []
    for stage, label in (('stage_1_full_grid', 'Full grid'),
                         ('stage_2_depth_only', 'Depth only')):
        for entry in settled.get(stage, []):
            scope = entry.get('scope') or {}
            rows.append({
                'Condition': C.condition_label(entry['name']),
                'Run in': label,
                'Level axis': ('fraction of labels clipped'
                               if entry['name'].startswith('censoring')
                               else 'fraction of the clean label spread'),
                'Scope': (f"{scope.get('n_pairs', '')} named pairs"
                          if scope.get('mode') == 'pair_subset'
                          else 'every model and representation'),
                'Why it is in the study': ' '.join(
                    str(entry.get('why', entry.get('rationale', ''))).split())[:400],
            })
    table = pd.DataFrame(rows)
    return write(table, output_dir, 'T2_noise_conditions',
                 'The settled noise conditions, read from noise_conditions.json '
                 '-- the file both injectors are tested against.')


# ---------------------------------------------------------------------------
# T3 -- the variance decomposition
# ---------------------------------------------------------------------------

def t3_variance(anova, output_dir, dataset='qm9'):
    """One row per condition and outcome, with the replicate spread beside each
    share. No version of this table has ever carried the spread."""
    if anova is None or not len(anova):
        return None
    frame = anova.copy()
    rows = []
    for _, r in frame.iterrows():
        row = {'Condition': C.condition_label(r['condition']),
               'Outcome': r['outcome']}
        for column, label in (('eta2_model', 'Model'),
                              ('eta2_rep', 'Representation'),
                              ('eta2_interaction', 'Interaction'),
                              ('eta2_residual', 'Residual')):
            spread = r.get(f'{column}_spread')
            row[f'{label} η² (%)'] = (
                f"{r[column]:.1f}" if not np.isfinite(spread or np.nan)
                else f"{r[column]:.1f} ± {spread / 2:.1f}")
        row['Models'] = int(r.get('n_models', 0))
        row['Representations'] = int(r.get('n_reps', 0))
        row['Replicates'] = int(r.get('n_replicates', 0))
        rows.append(row)
    table = pd.DataFrame(rows)
    return write(table, output_dir, f'T3_variance_decomposition_{dataset}',
                 'Share of variance explained by model, representation, their '
                 'pairing and the residual, per noise condition. The ± is half '
                 'the range across replicates: the decomposition is repeated on '
                 'each replicate separately. The assay datasets have no true '
                 'replicates and their version of this table has no residual '
                 'term for that reason.')


# ---------------------------------------------------------------------------
# T4 -- AUC_norm by model and condition
# ---------------------------------------------------------------------------

def t4_robustness(summary, output_dir, rep, dataset='qm9'):
    """Models down the side, conditions across, clean accuracy at the left.

    NO MEAN COLUMN, and the clean column is not optional: guard 4 refuses a
    ratio printed without its denominator, and this is the ratio the paper's
    headline rests on.
    """
    frame = summary[(summary['dataset'] == dataset) & (summary['rep'] == rep)]
    if not len(frame):
        return None
    G.declare(frame, 'T4', fixed={'dataset': dataset, 'rep': rep},
              varies=('model', 'condition'))
    conditions = C.sort_conditions(frame['condition'].unique())
    wide = frame.pivot_table(index='model', columns='condition',
                             values='auc_norm', aggfunc='median')
    wide = wide.reindex(index=C.sort_models(wide.index),
                        columns=[c for c in conditions if c in wide.columns])
    baseline = frame.groupby('model')['baseline_r2'].median()
    table = pd.DataFrame({'Model': [C.model_label(m) for m in wide.index]})
    table['Clean R²'] = baseline.reindex(wide.index).to_numpy()
    for condition in wide.columns:
        table[C.condition_label(condition)] = wide[condition].to_numpy()
    return write(table, output_dir, f'T4_robustness_{dataset}_{rep}',
                 f'Robustness (AUC_norm) by model and noise condition on '
                 f'{C.dataset_label(dataset)}, {C.rep_label(rep)}. The first '
                 f'column is the clean accuracy each figure is a fraction of. '
                 f'There is deliberately no mean column: a mean across noise '
                 f'conditions describes none of them.')


# ---------------------------------------------------------------------------
# T5 -- the probabilistic transformations
# ---------------------------------------------------------------------------

def t5_probabilistic(pairs, output_dir):
    """One row per pair and condition, one column per representation.

    The submitted paper's version carries a single number per row, which is a
    mean across representations -- the same averaging defect in miniature.
    """
    if pairs is None or not len(pairs):
        return None
    rows = []
    for (base, variant, condition), group in pairs.groupby(
            ['base', 'variant', 'condition']):
        row = {'Comparison': f'{C.model_label(base)} → {C.model_label(variant)}',
               'Condition': C.condition_label(condition)}
        for _, r in group.iterrows():
            mark = '*' if r.get('significant') else ''
            change = r.get('median_change')
            row[C.rep_label(r['rep'])] = (
                f'{change:+.3f}{mark}' if np.isfinite(change or np.nan) else '—')
        row['Pairs'] = int(group['n_pairs'].max())
        rows.append(row)
    table = pd.DataFrame(rows)
    return write(table, output_dir, 'T5_probabilistic_transformations',
                 'Change in robustness from replacing a model with its '
                 'probabilistic counterpart, paired on the replicate. One '
                 'column per representation and no averaging across them. '
                 '* marks a two-sided signed-rank test below 0.05; note that on '
                 'five pairs such a test cannot go below 0.0625 however large '
                 'the effect.')


# ---------------------------------------------------------------------------
# T6 -- uncertainty
# ---------------------------------------------------------------------------

def t6_uncertainty(support, q4, q6, slopes, output_dir):
    """One row per model and representation, with the support flags.

    A component flagged as one number per fit gets its flag printed and no
    slope, because a slope through a constant is arithmetic about the fit rather
    than a property of the molecules.
    """
    if support is None or not len(support):
        return None
    table = support[['dataset', 'model', 'rep', 'aleatoric_support',
                     'epistemic_support']].drop_duplicates().copy()
    table['Model'] = table['model'].map(C.model_label)
    table['Representation'] = table['rep'].map(C.rep_label)

    if q6 is not None and len(q6):
        rho = (q6.groupby(['dataset', 'model', 'rep'])['rho_unc_vs_clean_error']
               .median().rename('ρ(uncertainty, error)'))
        table = table.merge(rho, on=['dataset', 'model', 'rep'], how='left')
    if q4 is not None and len(q4):
        keep = ['dataset', 'model', 'rep']
        got = q4.groupby(keep)[['auc_error', 'auc_ratio', 'auc_delta']] \
            .median().reset_index()
        if 'outside_null' in q4.columns:
            fires = q4.groupby(keep)['outside_null'].any().rename('Outside null')
            got = got.merge(fires, on=keep, how='left')
        table = table.merge(got, on=keep, how='left')
    if slopes is not None and len(slopes):
        keep = [c for c in ('dataset', 'model', 'rep') if c in slopes.columns]
        got = (slopes.groupby(keep)[['slope_aleatoric', 'slope_epistemic']]
               .median().reset_index()
               if {'slope_aleatoric', 'slope_epistemic'} <= set(slopes.columns)
               else None)
        if got is not None:
            table = table.merge(got, on=keep, how='left')

    ordered = ['Model', 'Representation', 'aleatoric_support',
               'epistemic_support']
    ordered += [c for c in table.columns if c not in ordered
                and c not in ('dataset', 'model', 'rep')]
    table = table[ordered].rename(columns={
        'aleatoric_support': 'Aleatoric varies', 'epistemic_support':
        'Epistemic varies', 'auc_error': 'AUC (error alone)',
        'auc_ratio': 'AUC (error ÷ uncertainty)', 'auc_delta': 'Δ AUC',
        'slope_aleatoric': 'Aleatoric slope',
        'slope_epistemic': 'Epistemic slope'})
    return write(table, output_dir, 'T6_uncertainty',
                 'Uncertainty statistics per model and representation. The two '
                 'support columns say whether each component varies per '
                 'molecule or is one number per fit; a component that does not '
                 'vary has no slope, because a slope through a constant '
                 'describes the fit and not the molecules. Δ AUC is the gain '
                 'from dividing the error by the uncertainty; zero means the '
                 'uncertainty added nothing.')


# ---------------------------------------------------------------------------
# T7 -- rank transfer
# ---------------------------------------------------------------------------

def t7_rank_transfer(transfer, output_dir, rep=None, condition='gaussian'):
    """Each model's robustness rank on QM9 beside its rank on each assay set.

    ONE TABLE PER REPRESENTATION. The transfer question is exactly where
    averaging over representations would hide the answer.
    """
    if transfer is None or not len(transfer):
        return None
    # ONE table per representation, at the reference condition. Every
    # representation crossed with every condition is eighteen files, which is
    # not a table set, it is a directory. The full long form is already written
    # as d9_rank_transfer.csv for anyone who wants a different condition.
    available = set(transfer['condition'])
    use = condition if condition in available else sorted(available)[0]
    written = []
    for one_rep in sorted(transfer['rep'].unique()):
        if rep is not None and one_rep != rep:
            continue
        frame = transfer[transfer['rep'] == one_rep]
        for condition in [use]:
            sub = frame[frame['condition'] == condition]
            if not len(sub):
                continue
            wide = sub.pivot_table(index='model', columns='dataset',
                                   values='assay_rank')
            qm9 = sub.groupby('model')['qm9_rank'].first()
            table = pd.DataFrame({'Model': [C.model_label(m) for m in wide.index]})
            table['Rank on QM9'] = qm9.reindex(wide.index).to_numpy()
            for dataset in wide.columns:
                table[f'Rank on {C.dataset_label(dataset)}'] = \
                    wide[dataset].to_numpy()
            table['Largest change'] = (
                wide.sub(qm9.reindex(wide.index), axis=0).abs().max(axis=1)
                .to_numpy())
            written.append(write(
                table, output_dir,
                f'T7_rank_transfer_{one_rep}',
                f'Robustness rank on QM9 beside the rank on each assay dataset, '
                f'on {C.rep_label(one_rep)} under '
                f'{C.condition_label(condition)}, the reference condition. '
                f'One table per representation: '
                f'averaging over representations is exactly what would hide a '
                f'ranking that does not transfer.', float_format='%.0f'))
    return written[0] if written else None
